Dedoc: dedoc.converters.converter_composition.ConverterComposition Class Reference
dedoc.converters.converter_composition.ConverterComposition Class Reference
\par \b Purpose\/ \: To orchestrate a chain of format-specific converters, applying the first suitable one to a given file, so the caller does not need to know which converter handles which format.
Public Member Functions
None __init__ (self, List[AbstractConverter] converters)
\par \b Purpose\/ \: To initialize the converter chain with an ordered list of converters.
str convert (self, str file_path, Optional[dict] parameters=None, Optional[str] extension=None, Optional[str] mime=None)
\par \b Purpose\/ \: To convert a file using the first suitable converter from the chain, falling back to the original file if no converter matches.
Public Attributes
converters
Detailed Description
\par \b Purpose\/ \: To orchestrate a chain of format-specific converters, applying the first suitable one to a given file, so the caller does not need to know which converter handles which format.
This class allows to convert any document into the predefined list of formats according to the available list of converters. The list of converters is set via the class constructor. The first suitable converter is used (the one whose method :meth:~dedoc.converters.AbstractConverter.can_convert returns True), \ so the order of converters is important.
Constructor & Destructor Documentation
__init__()
None dedoc.converters.converter_composition.ConverterComposition.__init__ (self, List[AbstractConverter] converters)
\par \b Purpose\/ \: To initialize the converter chain with an ordered list of converters.
\par \b Uses\/ \: List, AbstractConverter \par \b I/O\/ \: converters: List[AbstractConverter] -> None \par \b Complexity\/ \: 1
:param converters: the list of converters that have methods can_convert() and convert(), they are used for files converting into specified formats
References dedoc.converters.converter_composition.ConverterComposition.convert().
Referenced by dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
convert()
str dedoc.converters.converter_composition.ConverterComposition.convert (self, str file_path, Optional[dict] parameters = None, Optional[str] extension = None, Optional[str] mime = None)
\par \b Purpose\/ \: To convert a file using the first suitable converter from the chain, falling back to the original file if no converter matches.
\par \b Uses\/ \: os, stat, get_mime_extension, AbstractConverter.can_convert, AbstractConverter.convert \par \b I/O\/ \: file_path: str, parameters: Optional[dict], extension: Optional[str], mime: Optional[str] -> str \par \b Complexity\/ \: 5
Convert file if there is the converter that can do it. If there isn't any converter that is able to convert the file, it isn't changed.
:param file_path: path of the file to convert :param parameters: parameters of converting, see :ref:parameters_description for more details :param extension: file extension, for example .doc or .pdf :param mime: MIME type of file :return: path of converted file if conversion was executed else path of the original file
References dedoc.converters.converter_composition.ConverterComposition.converters.
Referenced by dedoc.converters.converter_composition.ConverterComposition.__init__().
Member Data Documentation
converters
dedoc.converters.converter_composition.ConverterComposition.converters
Referenced by dedoc.converters.converter_composition.ConverterComposition.convert().
The documentation for this class was generated from the following file:
dedoc/converters/converter_composition.py