Dedoc: dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor Class Reference
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor Class Reference
Public Member Functions
None __init__ (self, *dict config)
Optional[PageWithBBox] extract_text_layer (self, str path, int page_number, ParametersForParseDoc parameters)
Extract text information with metadata from pdf with help pdfminer.six :param path: path to pdf :param page_number: number of the page to read :param parameters: parameters of document parsing :return: pages_with_bbox - page with extracted text.
Public Member Functions inherited from dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_extractor.PdfminerExtractor
None __init__ (self, *dict config)
Optional[PageWithBBox] extract_text_layer (self, str path, int page_number, ParametersForParseDoc parameters)
Extract text information with metadata from pdf with help pdfminer.six :param path: path to pdf :param page_number: number of the page to read :param parameters: parameters of document parsing :return: pages_with_bbox - page with extracted text.
TextWithBBox get_info_layout_object (self, LTContainer lobj, int page_num, int line_num, float k_w, float k_h, int height, int width)
Public Attributes
layout_corrector
cache
Public Attributes inherited from dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_extractor.PdfminerExtractor
config
logger
Additional Inherited Members
Static Public Member Functions inherited from dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_extractor.PdfminerExtractor
Iterator[PDFPage] get_pages (BinaryIO fp)
Protected Member Functions inherited from dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_extractor.PdfminerExtractor
PageWithBBox _handle_page (self, PDFPage page, int page_number, str path, ParametersForParseDoc parameters, Optional[LTPage] layout=None)
str _get_new_weight (self)
Constructor & Destructor Documentation
__init__()
None dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor.__init__ (self, *dict config)
Reimplemented from dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_extractor.PdfminerExtractor.
References dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor.__init__().
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor.__init__(), and dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
extract_text_layer()
Optional[PageWithBBox] dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor.extract_text_layer (self, str path, int page_number, ParametersForParseDoc parameters)
Extract text information with metadata from pdf with help pdfminer.six :param path: path to pdf :param page_number: number of the page to read :param parameters: parameters of document parsing :return: pages_with_bbox - page with extracted text.
Reimplemented from dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_extractor.PdfminerExtractor.
References dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_extractor.PdfminerExtractor._handle_page(), dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor.cache, and dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor.layout_corrector.
Member Data Documentation
cache
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor.cache
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor.extract_text_layer().
layout_corrector
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor.layout_corrector
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.broken_encoding_extractor.BrokenEncodingExtractor.extract_text_layer().
The documentation for this class was generated from the following file:
dedoc/readers/pdf_reader/pdf_txtlayer_reader/pdf_broken_encoding/broken_encoding_extractor.py