Dedoc: dedoc.api.schema.line_metadata.LineMetadata Class Reference
dedoc.api.schema.line_metadata.LineMetadata Class Reference
\par \b Purpose\/ \: Hold paragraph/line-level metadata (type, page, line number) with extensible extra attributes for format-specific annotations.
Classes
class Config
Static Public Attributes
str
description
example
int page_id = Field(description="Page number of the line/paragraph beginning", example=0)
Optional line_id = Field(description="Line number", example=1)
Detailed Description
\par \b Purpose\/ \: Hold paragraph/line-level metadata (type, page, line number) with extensible extra attributes for format-specific annotations.
\par \b I/O\/ \: (paragraph_type, page_id, line_id, **extra) -> JSON serializable model
Holds information about document node/line metadata, such as page number or line type.
:ivar paragraph_type: type of the document line/paragraph (header, list_item, list, etc.) :ivar page_id: page number where paragraph starts, the numeration starts from page 0 :ivar line_id: line number inside the entire document, the numeration starts from line 0
:vartype paragraph_type: str :vartype page_id: int :vartype line_id: Optional[int]
Additional variables may be added with other line metadata.
Member Data Documentation
description
dedoc.api.schema.line_metadata.LineMetadata.description static
example
dedoc.api.schema.line_metadata.LineMetadata.example static
line_id
Optional dedoc.api.schema.line_metadata.LineMetadata.line_id = Field(description="Line number", example=1) static
Referenced by dedoc.data_structures.line_metadata.LineMetadata.__init__(), and dedoc.data_structures.line_metadata.LineMetadata.to_api_schema().
page_id
int dedoc.api.schema.line_metadata.LineMetadata.page_id = Field(description="Page number of the line/paragraph beginning", example=0) static
Referenced by dedoc.data_structures.line_metadata.LineMetadata.__init__(), dedoc.data_structures.table_metadata.TableMetadata.__init__(), dedoc.readers.pptx_reader.shape.PptxShape.get_lines(), dedoc.data_structures.line_metadata.LineMetadata.to_api_schema(), dedoc.data_structures.table_metadata.TableMetadata.to_api_schema(), and dedoc.readers.pptx_reader.table.PptxTable.to_table().
str
dedoc.api.schema.line_metadata.LineMetadata.str static
The documentation for this class was generated from the following file:
dedoc/api/schema/line_metadata.py