Dedoc: dedoc.data_structures.concrete_annotations.subscript_annotation.SubscriptAnnotation Class Reference
dedoc.data_structures.concrete_annotations.subscript_annotation.SubscriptAnnotation Class Reference
\par \b Purpose\/ \: Mark subscript text inside the line.
Public Member Functions
None __init__ (self, int start, int end, str value)
\par \b Purpose\/ \: Initialize subscript annotation with validated boolean value.
Public Member Functions inherited from dedoc.data_structures.annotation.Annotation
None __init__ (self, int start, int end, str name, str value, bool is_mergeable=True)
\par \b Purpose\/ \: Initialize annotation with position, name, value, and mergeability flag.
bool __eq__ (self, object o)
\par \b Purpose\/ \: Compare two annotations for equality by name, value, start, and end.
str __str__ (self)
\par \b Purpose\/ \: Return human-readable string representation of the annotation.
str __repr__ (self)
\par \b Purpose\/ \: Return repr of the annotation (delegates to str).
ApiAnnotation to_api_schema (self)
\par \b Purpose\/ \: Convert annotation to API schema representation.
BaseModel to_api_schema (self)
\par \b Purpose\/ \: Convert class data to the corresponding API schema Pydantic model.
Static Public Attributes
str name = "subscript"
list valid_values = ["True", "False"]
Additional Inherited Members
Public Attributes inherited from dedoc.data_structures.annotation.Annotation
name
Detailed Description
\par \b Purpose\/ \: Mark subscript text inside the line.
Subscript text inside the line.
Constructor & Destructor Documentation
__init__()
None dedoc.data_structures.concrete_annotations.subscript_annotation.SubscriptAnnotation.__init__ (self, int start, int end, str value)
\par \b Purpose\/ \: Initialize subscript annotation with validated boolean value.
\par \b Uses\/ \: Annotation.__init__ \par \b I/O\/ \: (int, int, str) -> None \par \b Complexity\/ \: 3
:param start: start of the subscript text :param end: end of the subscript text (not included) :param value: True if subscript else False (False usually isn't used because you may not use this annotation at all)
Reimplemented from dedoc.data_structures.annotation.Annotation.
References dedoc.data_structures.concrete_annotations.subscript_annotation.SubscriptAnnotation.__init__().
Referenced by dedoc.data_structures.concrete_annotations.subscript_annotation.SubscriptAnnotation.__init__(), and dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Data Documentation
name
str dedoc.data_structures.concrete_annotations.subscript_annotation.SubscriptAnnotation.name = "subscript" static
Referenced by dedoc.structure_extractors.feature_extractors.list_features.prefix.prefix.LinePrefix.__eq__(), dedoc.data_structures.annotation.Annotation.__init__(), dedoc.data_structures.annotation.Annotation.to_api_schema(), and dedoc.readers.pdf_reader.data_classes.tables.location.Location.to_dict().
valid_values
list dedoc.data_structures.concrete_annotations.subscript_annotation.SubscriptAnnotation.valid_values = ["True", "False"] static
The documentation for this class was generated from the following file:
dedoc/data_structures/concrete_annotations/subscript_annotation.py