Dedoc: dedoc.converters.concrete_converters.binary_converter.BinaryConverter Class Reference
dedoc.converters.concrete_converters.binary_converter.BinaryConverter Class Reference
\par \b Purpose\/ \: To convert binary blob files (mime=application/octet-stream) that carry image-like extensions (.bmp, .jpg, .tiff, etc.) into PNG by delegating to PNGConverter.
Public Member Functions
None __init__ (self, *Optional[dict] config=None)
\par \b Purpose\/ \: To initialize the converter and its internal PNGConverter delegate.
bool can_convert (self, Optional[str] file_path=None, Optional[str] extension=None, Optional[str] mime=None, Optional[dict] parameters=None)
\par \b Purpose\/ \: To detect image-like binary files by checking for mime=application/octet-stream combined with a known image extension.
str convert (self, str file_path, Optional[dict] parameters=None)
\par \b Purpose\/ \: To convert an image-like binary file to PNG by delegating to the internal PNGConverter.
None __init__ (self, *Optional[dict] config=None, Optional[Set[str]] converted_extensions=None, Optional[Set[str]] converted_mimes=None)
\par \b Purpose\/ \: To initialize the converter with configuration, supported extension sets, and a configurable timeout/watchdog period for subprocess calls.
bool can_convert (self, Optional[str] file_path=None, Optional[str] extension=None, Optional[str] mime=None, Optional[dict] parameters=None)
\par \b Purpose\/ \: To determine whether this converter can handle a file by matching its extension or MIME type against the converter's supported sets.
str convert (self, str file_path, Optional[dict] parameters=None)
\par \b Purpose\/ \: To convert a file to the target format.
Public Attributes
png_converter
Public Attributes inherited from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter
timeout
period_checking
config
logger
Additional Inherited Members
Protected Member Functions inherited from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter
None _run_subprocess (self, List[str] command, str filename, str expected_path)
\par \b Purpose\/ \: To execute an external conversion command with timeout handling, error extraction from stderr, and graceful ConversionError on failure.
Protected Attributes inherited from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter
_converted_extensions
_converted_mimes
Detailed Description
\par \b Purpose\/ \: To convert binary blob files (mime=application/octet-stream) that carry image-like extensions (.bmp, .jpg, .tiff, etc.) into PNG by delegating to PNGConverter.
Converts image-like documents with mime=application/octet-stream into PNG. Look to the :class:~dedoc.converters.AbstractConverter documentation to get the information about the methods' parameters.
Constructor & Destructor Documentation
__init__()
None dedoc.converters.concrete_converters.binary_converter.BinaryConverter.__init__ (self, *Optional[dict] config = None)
\par \b Purpose\/ \: To initialize the converter and its internal PNGConverter delegate.
\par \b Uses\/ \: PNGConverter \par \b I/O\/ \: config: Optional[dict] -> None \par \b Complexity\/ \: 2
Reimplemented from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter.
References dedoc.converters.concrete_converters.binary_converter.BinaryConverter.__init__().
Referenced by dedoc.converters.concrete_converters.binary_converter.BinaryConverter.__init__(), and dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
can_convert()
bool dedoc.converters.concrete_converters.binary_converter.BinaryConverter.can_convert (self, Optional[str] file_path = None, Optional[str] extension = None, Optional[str] mime = None, Optional[dict] parameters = None)
\par \b Purpose\/ \: To detect image-like binary files by checking for mime=application/octet-stream combined with a known image extension.
\par \b Uses\/ \: get_mime_extension, supported_image_types \par \b I/O\/ \: file_path: Optional[str], extension: Optional[str], mime: Optional[str], parameters: Optional[dict] -> bool \par \b Complexity\/ \: 3
Checks if the document is image-like (e.g. it has .bmp, .jpg, .tiff, etc. extension) and has mime=application/octet-stream.
Reimplemented from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter.
convert()
str dedoc.converters.concrete_converters.binary_converter.BinaryConverter.convert (self, str file_path, Optional[dict] parameters = None)
\par \b Purpose\/ \: To convert an image-like binary file to PNG by delegating to the internal PNGConverter.
\par \b Uses\/ \: PNGConverter.convert \par \b I/O\/ \: file_path: str, parameters: Optional[dict] -> str \par \b Complexity\/ \: 2
Convert the image-like and application/octet-stream documents into files with .png extension.
Reimplemented from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter.
References dedoc.converters.concrete_converters.binary_converter.BinaryConverter.convert(), and dedoc.converters.concrete_converters.binary_converter.BinaryConverter.png_converter.
Referenced by dedoc.converters.concrete_converters.binary_converter.BinaryConverter.convert().
Member Data Documentation
png_converter
dedoc.converters.concrete_converters.binary_converter.BinaryConverter.png_converter
Referenced by dedoc.converters.concrete_converters.binary_converter.BinaryConverter.convert().
The documentation for this class was generated from the following file:
dedoc/converters/concrete_converters/binary_converter.py