Dedoc: dedoc.readers.pdf_reader.pdf_image_reader.line_metadata_extractor.bold_classifier.valley_emphasis_binarizer.ValleyEmphasisBinarizer Class Reference
dedoc.readers.pdf_reader.pdf_image_reader.line_metadata_extractor.bold_classifier.valley_emphasis_binarizer.ValleyEmphasisBinarizer Class Reference
Public Member Functions
None __init__ (self, int n=5)
np.ndarray binarize (self, np.ndarray image)
Public Attributes
n
Private Member Functions
int __get_threshold (self, np.ndarray gray_img)
Constructor & Destructor Documentation
__init__()
None dedoc.readers.pdf_reader.pdf_image_reader.line_metadata_extractor.bold_classifier.valley_emphasis_binarizer.ValleyEmphasisBinarizer.__init__ (self, int n = 5)
Referenced by dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
__get_threshold()
int dedoc.readers.pdf_reader.pdf_image_reader.line_metadata_extractor.bold_classifier.valley_emphasis_binarizer.ValleyEmphasisBinarizer.__get_threshold (self, np.ndarray gray_img) private
References dedoc.readers.pdf_reader.pdf_image_reader.line_metadata_extractor.bold_classifier.valley_emphasis_binarizer.ValleyEmphasisBinarizer.n.
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.line_metadata_extractor.bold_classifier.valley_emphasis_binarizer.ValleyEmphasisBinarizer.binarize().
binarize()
np.ndarray dedoc.readers.pdf_reader.pdf_image_reader.line_metadata_extractor.bold_classifier.valley_emphasis_binarizer.ValleyEmphasisBinarizer.binarize (self, np.ndarray image)
References dedoc.readers.pdf_reader.pdf_image_reader.line_metadata_extractor.bold_classifier.valley_emphasis_binarizer.ValleyEmphasisBinarizer.__get_threshold().
Member Data Documentation
n
dedoc.readers.pdf_reader.pdf_image_reader.line_metadata_extractor.bold_classifier.valley_emphasis_binarizer.ValleyEmphasisBinarizer.n
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.line_metadata_extractor.bold_classifier.valley_emphasis_binarizer.ValleyEmphasisBinarizer.__get_threshold().
The documentation for this class was generated from the following file:
dedoc/readers/pdf_reader/pdf_image_reader/line_metadata_extractor/bold_classifier/valley_emphasis_binarizer.py