Dedoc: dedoc.readers.pdf_reader.pdf_image_reader.columns_orientation_classifier.model.ClassificationModelTorch Class Reference
dedoc.readers.pdf_reader.pdf_image_reader.columns_orientation_classifier.model.ClassificationModelTorch Class Reference
Class detects EfficientNet B0 model.
Public Member Functions
None __init__ (self, Optional[str] model_path, int num_classes=6)
first 2 classes mean columns number last 4 classes mean orientation
torch.Tensor forward (self, torch.Tensor x)
Public Attributes
efficientnet_b0
Detailed Description
Class detects EfficientNet B0 model.
Constructor & Destructor Documentation
__init__()
None dedoc.readers.pdf_reader.pdf_image_reader.columns_orientation_classifier.model.ClassificationModelTorch.__init__ (self, Optional[str] model_path, int num_classes = 6)
first 2 classes mean columns number last 4 classes mean orientation
References dedoc.readers.pdf_reader.pdf_image_reader.columns_orientation_classifier.model.ClassificationModelTorch.__init__().
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.columns_orientation_classifier.model.ClassificationModelTorch.__init__(), and dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
forward()
torch.Tensor dedoc.readers.pdf_reader.pdf_image_reader.columns_orientation_classifier.model.ClassificationModelTorch.forward (self, torch.Tensor x)
References dedoc.readers.pdf_reader.pdf_image_reader.columns_orientation_classifier.model.ClassificationModelTorch.efficientnet_b0.
Member Data Documentation
efficientnet_b0
dedoc.readers.pdf_reader.pdf_image_reader.columns_orientation_classifier.model.ClassificationModelTorch.efficientnet_b0
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.columns_orientation_classifier.model.ClassificationModelTorch.forward().
The documentation for this class was generated from the following file:
dedoc/readers/pdf_reader/pdf_image_reader/columns_orientation_classifier/model.py