Dedoc: dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor Class Reference
dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor Class Reference
\par \b Purpose\/ \: Build the primary hierarchical document structure: construct a tree from lines with hierarchy levels, merging headers, and inserting auxiliary list nodes.
Public Member Functions
ParsedDocument construct (self, UnstructuredDocument document, Optional[dict] parameters=None)
\par \b Purpose\/ \: Build the full hierarchical tree: extract document name, insert list auxiliary nodes, add lines with hierarchy-aware positioning, merge root.
ParsedDocument construct (self, UnstructuredDocument document, Optional[dict] parameters=None)
\par \b Purpose\/ \: Transform an intermediate UnstructuredDocument into a final ParsedDocument by applying the specific structure construction algorithm.
Private Member Functions
Tuple[List[LineWithMeta], List[LineWithMeta]] __get_document_name (self, List[LineWithMeta] lines)
\par \b Purpose\/ \: Separate lines with hierarchy level (0, 0) (document title/name) from all other content lines.
List[LineWithMeta] __add_lists (self, List[LineWithMeta] not_document_name)
\par \b Purpose\/ \: Insert auxiliary "list" nodes before consecutive list-item lines that share the same hierarchy level.
Static Private Member Functions
LineWithMeta __create_list_line (LineWithMeta line)
\par \b Purpose\/ \: Create an auxiliary "list" line with adjusted hierarchy level (level_2 -= 0.5) to serve as a container for list-item children.
Detailed Description
\par \b Purpose\/ \: Build the primary hierarchical document structure: construct a tree from lines with hierarchy levels, merging headers, and inserting auxiliary list nodes.
This class is used to form a basic hierarchical document structure representation as a tree.
The structure is built according to the lines' hierarchy levels and their types:
lines with hierarchy level (0, 0) are merged and become a root of the document;
lines with a type list_item become children of a new empty auxiliary node list;
each line is added as a separate tree node in the document hierarchy according to its hierarchy level:
if the level of the current line is less then the previous line level, the current line becomes its child;
else the line becomes a child of the first line which have less hierarchy level that the current line has.
Hierarchy levels of the lines are compared lexicographically.
Example:
root line (0, 0)
first child line (1, 0)
line (2, 0)
line (2, 1)
line (2, 0)
second child line (1, 0)
Member Function Documentation
__add_lists()
List[LineWithMeta] dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor.__add_lists (self, List[LineWithMeta] not_document_name) private
\par \b Purpose\/ \: Insert auxiliary "list" nodes before consecutive list-item lines that share the same hierarchy level.
\par \b Uses\/ \: LineWithMeta, __create_list_line, HierarchyLevel.is_list_item \par \b I/O\/ \: List[LineWithMeta] -> List[LineWithMeta] \par \b Complexity\/ \: 6
References dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor.__create_list_line().
Referenced by dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor.construct().
__create_list_line()
LineWithMeta dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor.__create_list_line (LineWithMeta line) static private
\par \b Purpose\/ \: Create an auxiliary "list" line with adjusted hierarchy level (level_2 -= 0.5) to serve as a container for list-item children.
\par \b Uses\/ \: HierarchyLevel, LineMetadata, LineWithMeta \par \b I/O\/ \: LineWithMeta -> LineWithMeta \par \b Complexity\/ \: 3
Referenced by dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor.__add_lists().
__get_document_name()
Tuple[List[LineWithMeta], List[LineWithMeta]] dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor.__get_document_name (self, List[LineWithMeta] lines) private
\par \b Purpose\/ \: Separate lines with hierarchy level (0, 0) (document title/name) from all other content lines.
\par \b Uses\/ \: LineWithMeta \par \b I/O\/ \: List[LineWithMeta] -> Tuple[List[LineWithMeta], List[LineWithMeta]] \par \b Complexity\/ \: 3
Referenced by dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor.construct().
construct()
ParsedDocument dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor.construct (self, UnstructuredDocument document, Optional[dict] parameters = None)
\par \b Purpose\/ \: Build the full hierarchical tree: extract document name, insert list auxiliary nodes, add lines with hierarchy-aware positioning, merge root.
\par \b Uses\/ \: TreeNode, DocumentContent, DocumentMetadata, __get_document_name, __add_lists \par \b I/O\/ \: UnstructuredDocument, Optional[dict] -> ParsedDocument \par \b Complexity\/ \: 8
Build the tree structure representation for the given document intermediate representation. To get the information about the parameters look at the documentation of :class:~dedoc.structure_constructors.AbstractStructureConstructor.
Reimplemented from dedoc.structure_constructors.abstract_structure_constructor.AbstractStructureConstructor.
References dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor.__add_lists(), and dedoc.structure_constructors.concrete_structure_constructors.tree_constructor.TreeConstructor.__get_document_name().
The documentation for this class was generated from the following file:
dedoc/structure_constructors/concrete_structure_constructors/tree_constructor.py