Dedoc: dedoc.common.exceptions.dedoc_error.DedocError Class Reference
dedoc.common.exceptions.dedoc_error.DedocError Class Reference
\par \b Purpose\/ \: To provide a unified, serializable error base class that all dedoc-specific exceptions inherit from, enabling consistent API error responses with rich metadata.
Public Member Functions
None __init__ (self, str msg, Optional[str] msg_api=None, Optional[str] filename=None, Optional[str] version=None, Optional[dict] metadata=None, Optional[int] code=None)
\par \b Purpose\/ \: To initialize a DedocError with full error context — message, API message, filename, version, metadata, and HTTP status code.
str __str__ (self)
\par \b Purpose\/ \: To provide a human-readable string representation of the error for logging and debugging.
Static Public Member Functions
"DedocError" from_dict (dict error_dict)
\par \b Purpose\/ \: To reconstruct a DedocError instance from a dictionary, enabling error deserialization from JSON responses or stored error records.
Public Attributes
msg
msg_api
filename
version
metadata
code
Detailed Description
\par \b Purpose\/ \: To provide a unified, serializable error base class that all dedoc-specific exceptions inherit from, enabling consistent API error responses with rich metadata.
Constructor & Destructor Documentation
__init__()
None dedoc.common.exceptions.dedoc_error.DedocError.__init__ (self, str msg, Optional[str] msg_api = None, Optional[str] filename = None, Optional[str] version = None, Optional[dict] metadata = None, Optional[int] code = None)
\par \b Purpose\/ \: To initialize a DedocError with full error context — message, API message, filename, version, metadata, and HTTP status code.
\par \b Uses\/ \: dedoc.version \par \b I/O\/ \: (msg: str, msg_api: Optional[str], filename: Optional[str], version: Optional[str], metadata: Optional[dict], code: Optional[int]) -> None \par \b Complexity\/ \: 4
Reimplemented in dedoc.common.exceptions.bad_file_error.BadFileFormatError, dedoc.common.exceptions.bad_parameters_error.BadParametersError, dedoc.common.exceptions.conversion_error.ConversionError, dedoc.common.exceptions.java_not_found_error.JavaNotFoundError, dedoc.common.exceptions.missing_file_error.MissingFileError, dedoc.common.exceptions.recognize_error.RecognizeError, dedoc.common.exceptions.structure_extractor_error.StructureExtractorError, and dedoc.common.exceptions.tabby_pdf_error.TabbyPdfError.
References dedoc.common.exceptions.dedoc_error.DedocError.__init__().
Referenced by dedoc.common.exceptions.dedoc_error.DedocError.__init__(), and dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
__str__()
str dedoc.common.exceptions.dedoc_error.DedocError.__str__ (self)
\par \b Purpose\/ \: To provide a human-readable string representation of the error for logging and debugging.
\par \b I/O\/ \: None -> str \par \b Complexity\/ \: 1
Reimplemented in dedoc.common.exceptions.bad_file_error.BadFileFormatError, dedoc.common.exceptions.bad_parameters_error.BadParametersError, dedoc.common.exceptions.conversion_error.ConversionError, dedoc.common.exceptions.java_not_found_error.JavaNotFoundError, dedoc.common.exceptions.missing_file_error.MissingFileError, dedoc.common.exceptions.recognize_error.RecognizeError, dedoc.common.exceptions.structure_extractor_error.StructureExtractorError, and dedoc.common.exceptions.tabby_pdf_error.TabbyPdfError.
Referenced by dedoc.data_structures.annotation.Annotation.__repr__(), dedoc.readers.pdf_reader.data_classes.tables.cell.Cell.__repr__(), dedoc.readers.pdf_reader.data_classes.text_with_bbox.TextWithBBox.__repr__(), dedoc.readers.pdf_reader.data_classes.word_with_bbox.WordWithBBox.__repr__(), and dedoc.structure_extractors.feature_extractors.list_features.prefix.prefix.LinePrefix.__repr__().
from_dict()
"DedocError" dedoc.common.exceptions.dedoc_error.DedocError.from_dict (dict error_dict) static
\par \b Purpose\/ \: To reconstruct a DedocError instance from a dictionary, enabling error deserialization from JSON responses or stored error records.
\par \b Uses\/ \: dedoc.version \par \b I/O\/ \: dict -> DedocError \par \b Complexity\/ \: 4
Member Data Documentation
code
dedoc.common.exceptions.dedoc_error.DedocError.code
filename
dedoc.common.exceptions.dedoc_error.DedocError.filename
metadata
dedoc.common.exceptions.dedoc_error.DedocError.metadata
Referenced by dedoc.data_structures.line_with_meta.LineWithMeta.__getitem__(), dedoc.data_structures.parsed_document.ParsedDocument.__init__(), dedoc.data_structures.table.Table.__init__(), dedoc.data_structures.unstructured_document.UnstructuredDocument.__init__(), dedoc.data_structures.tree_node.TreeNode.__init__(), dedoc.data_structures.line_with_meta.LineWithMeta.__repr__(), dedoc.data_structures.tree_node.TreeNode.add_text(), dedoc.data_structures.parsed_document.ParsedDocument.to_api_schema(), dedoc.data_structures.table.Table.to_api_schema(), dedoc.data_structures.tree_node.TreeNode.to_api_schema(), and dedoc.readers.pdf_reader.data_classes.tables.scantable.ScanTable.uid().
msg
dedoc.common.exceptions.dedoc_error.DedocError.msg
msg_api
dedoc.common.exceptions.dedoc_error.DedocError.msg_api
version
dedoc.common.exceptions.dedoc_error.DedocError.version
The documentation for this class was generated from the following file:
dedoc/common/exceptions/dedoc_error.py