Dedoc: dedoc.data_structures.concrete_annotations.color_annotation.ColorAnnotation Class Reference
dedoc.data_structures.concrete_annotations.color_annotation.ColorAnnotation Class Reference
\par \b Purpose\/ \: Mark color of some text inside the line in RGB format.
Public Member Functions
None __init__ (self, int start, int end, float red, float green, float blue)
\par \b Purpose\/ \: Initialize color annotation with validated RGB values.
str __str__ (self)
\par \b Purpose\/ \: Return string representation of the color annotation.
Public Member Functions inherited from dedoc.data_structures.annotation.Annotation
None __init__ (self, int start, int end, str name, str value, bool is_mergeable=True)
\par \b Purpose\/ \: Initialize annotation with position, name, value, and mergeability flag.
bool __eq__ (self, object o)
\par \b Purpose\/ \: Compare two annotations for equality by name, value, start, and end.
str __str__ (self)
\par \b Purpose\/ \: Return human-readable string representation of the annotation.
str __repr__ (self)
\par \b Purpose\/ \: Return repr of the annotation (delegates to str).
ApiAnnotation to_api_schema (self)
\par \b Purpose\/ \: Convert annotation to API schema representation.
BaseModel to_api_schema (self)
\par \b Purpose\/ \: Convert class data to the corresponding API schema Pydantic model.
Public Attributes
red
blue
green
Public Attributes inherited from dedoc.data_structures.annotation.Annotation
name
Static Public Attributes
str name = "color_annotation"
Detailed Description
\par \b Purpose\/ \: Mark color of some text inside the line in RGB format.
Color of some text inside the line in the RGB format.
Constructor & Destructor Documentation
__init__()
None dedoc.data_structures.concrete_annotations.color_annotation.ColorAnnotation.__init__ (self, int start, int end, float red, float green, float blue)
\par \b Purpose\/ \: Initialize color annotation with validated RGB values.
\par \b Uses\/ \: Annotation.__init__, json \par \b I/O\/ \: (int, int, float, float, float) -> None \par \b Complexity\/ \: 4
:param start: start of the colored text :param end: end of the colored text (not included) :param red: mean value of the red color component in the pixels that are not white in the given bounding box :param green: mean value of the green color component in the pixels that are not white in the given bounding box :param blue: mean value of the blue color component in the pixels that are not white in the given bounding box
Reimplemented from dedoc.data_structures.annotation.Annotation.
Referenced by dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
__str__()
str dedoc.data_structures.concrete_annotations.color_annotation.ColorAnnotation.__str__ (self)
\par \b Purpose\/ \: Return string representation of the color annotation.
\par \b I/O\/ \: None -> str \par \b Complexity\/ \: 1
Reimplemented from dedoc.data_structures.annotation.Annotation.
Referenced by dedoc.data_structures.annotation.Annotation.__repr__(), dedoc.readers.pdf_reader.data_classes.tables.cell.Cell.__repr__(), dedoc.readers.pdf_reader.data_classes.text_with_bbox.TextWithBBox.__repr__(), dedoc.readers.pdf_reader.data_classes.word_with_bbox.WordWithBBox.__repr__(), and dedoc.structure_extractors.feature_extractors.list_features.prefix.prefix.LinePrefix.__repr__().
Member Data Documentation
blue
dedoc.data_structures.concrete_annotations.color_annotation.ColorAnnotation.blue
green
dedoc.data_structures.concrete_annotations.color_annotation.ColorAnnotation.green
name
str dedoc.data_structures.concrete_annotations.color_annotation.ColorAnnotation.name = "color_annotation" static
Referenced by dedoc.structure_extractors.feature_extractors.list_features.prefix.prefix.LinePrefix.__eq__(), dedoc.data_structures.annotation.Annotation.__init__(), dedoc.data_structures.annotation.Annotation.to_api_schema(), and dedoc.readers.pdf_reader.data_classes.tables.location.Location.to_dict().
red
dedoc.data_structures.concrete_annotations.color_annotation.ColorAnnotation.red
The documentation for this class was generated from the following file:
dedoc/data_structures/concrete_annotations/color_annotation.py