Dedoc: dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor Class Reference
dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor Class Reference
\par \b Purpose\/ \: Abstract base class for Office-format (docx, xlsx, pptx) attachment extraction: OLE binary parsing and ZIP-based media collection.
Public Member Functions
None __init__ (self, *Optional[dict] config=None, Optional[Set[str]] recognized_extensions=None, Optional[Set[str]] recognized_mimes=None)
\par \b Purpose\/ \: Initialize with config and recognized extensions/mimes, delegating to the parent AbstractAttachmentsExtractor.
Public Member Functions inherited from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor
None __init__ (self, *Optional[dict] config=None, Optional[Set[str]] recognized_extensions=None, Optional[Set[str]] recognized_mimes=None)
\par \b Purpose\/ \: Initialize the extractor with configuration, recognized file extensions, and recognized MIME types.
bool can_extract (self, Optional[str] file_path=None, Optional[str] extension=None, Optional[str] mime=None, Optional[dict] parameters=None)
\par \b Purpose\/ \: Determine whether this extractor can handle the given file based on its extension or MIME type.
List[AttachedFile] extract (self, str file_path, Optional[dict] parameters=None)
\par \b Purpose\/ \: Abstract method: extract attachments from the given file.
Protected Member Functions
List[AttachedFile] _get_attachments (self, str tmpdir, str filename, dict parameters, str attachments_dir)
\par \b Purpose\/ \: Extract all attachments from an Office-format ZIP archive: collect media/embeddings from the specified folder, parse .bin OLE files for embedded PDF or Ole10Native content.
Protected Member Functions inherited from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor
List[AttachedFile] _content2attach_file (self, List[Tuple[str, bytes]] content, str tmpdir, bool need_content_analysis, dict parameters)
\par \b Purpose\/ \: Convert a list of (filename, binary_data) tuples into a list of AttachedFile objects, saving binary data to unique files on disk.
Private Member Functions
Tuple[str, bytes] __parse_ole_contents (self, bytes stream)
\par \b Purpose\/ \: Parse the Ole10Native binary stream into the original filename and file contents.
Additional Inherited Members
Static Public Member Functions inherited from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor
bool with_attachments (dict parameters)
\par \b Purpose\/ \: Static helper: check if the 'with_attachments' parameter is truthy.
Public Attributes inherited from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor
config
logger
Protected Attributes inherited from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor
_recognized_extensions
_recognized_mimes
Detailed Description
\par \b Purpose\/ \: Abstract base class for Office-format (docx, xlsx, pptx) attachment extraction: OLE binary parsing and ZIP-based media collection.
Constructor & Destructor Documentation
__init__()
None dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor.__init__ (self, *Optional[dict] config = None, Optional[Set[str]] recognized_extensions = None, Optional[Set[str]] recognized_mimes = None)
\par \b Purpose\/ \: Initialize with config and recognized extensions/mimes, delegating to the parent AbstractAttachmentsExtractor.
\par \b I/O\/ \: Optional[dict], Optional[Set[str]], Optional[Set[str]] -> None \par \b Complexity\/ \: 2
Reimplemented from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor.
Reimplemented in dedoc.attachments_extractors.concrete_attachments_extractors.docx_attachments_extractor.DocxAttachmentsExtractor, dedoc.attachments_extractors.concrete_attachments_extractors.excel_attachments_extractor.ExcelAttachmentsExtractor, and dedoc.attachments_extractors.concrete_attachments_extractors.pptx_attachments_extractor.PptxAttachmentsExtractor.
References dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor.__init__().
Referenced by dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor.__init__(), and dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
__parse_ole_contents()
Tuple[str, bytes] dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor.__parse_ole_contents (self, bytes stream) private
\par \b Purpose\/ \: Parse the Ole10Native binary stream into the original filename and file contents.
\par \b Uses\/ \: charset_normalizer.from_bytes \par \b I/O\/ \: bytes -> Tuple[str, bytes] \par \b Complexity\/ \: 8
Referenced by dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor._get_attachments().
_get_attachments()
List[AttachedFile] dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor._get_attachments (self, str tmpdir, str filename, dict parameters, str attachments_dir) protected
\par \b Purpose\/ \: Extract all attachments from an Office-format ZIP archive: collect media/embeddings from the specified folder, parse .bin OLE files for embedded PDF or Ole10Native content.
\par \b Uses\/ \: olefile.OleFileIO, AbstractAttachmentsExtractor._content2attach_file \par \b I/O\/ \: str, str, dict, str -> List[AttachedFile] \par \b Complexity\/ \: 8
References dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor.__parse_ole_contents(), and dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor._content2attach_file().
Referenced by dedoc.attachments_extractors.concrete_attachments_extractors.docx_attachments_extractor.DocxAttachmentsExtractor.extract(), dedoc.attachments_extractors.concrete_attachments_extractors.excel_attachments_extractor.ExcelAttachmentsExtractor.extract(), and dedoc.attachments_extractors.concrete_attachments_extractors.pptx_attachments_extractor.PptxAttachmentsExtractor.extract().
The documentation for this class was generated from the following file:
dedoc/attachments_extractors/concrete_attachments_extractors/abstract_office_attachments_extractor.py