Dedoc: dedoc.api.schema.parsed_document.ParsedDocument Class Reference
dedoc.api.schema.parsed_document.ParsedDocument Class Reference
\par \b Purpose\/ \: Top-level API response model: aggregates document content, metadata, nested attachments, warnings, and version into a single JSON-serializable entity.
Static Public Attributes
DocumentContent content = Field(description="Document text and tables")
DocumentMetadata metadata = Field(description="Document metadata such as size, creation date and so on")
str version = Field(description="Version of the program that parsed this document", example="0.9.1")
List warnings = Field(description="List of warnings and possible errors, arising in the process of document parsing")
List attachments = Field(description="Result of analysis of attached files - list of `ParsedDocument`")
Detailed Description
\par \b Purpose\/ \: Top-level API response model: aggregates document content, metadata, nested attachments, warnings, and version into a single JSON-serializable entity.
\par \b I/O\/ \: (content, metadata, version, warnings, attachments) -> JSON serializable model
Holds information about the document content, metadata and attachments.
:ivar content: document text (hierarchy of nodes) and tables :ivar attachments: result of analysis of attached files (empty if with_attachments=False) :ivar metadata: document metadata such as size, creation date and so on. :ivar warnings: list of warnings and possible errors, arising in the process of document parsing :ivar version: version of the program that parsed this document
:vartype content: DocumentContent :vartype attachments: List[ParsedDocument] :vartype metadata: DocumentMetadata :vartype warnings: List[str] :vartype version: str
Member Data Documentation
attachments
List dedoc.api.schema.parsed_document.ParsedDocument.attachments = Field(description="Result of analysis of attached files - list of `ParsedDocument`") static
Referenced by dedoc.data_structures.parsed_document.ParsedDocument.__init__(), dedoc.data_structures.unstructured_document.UnstructuredDocument.__init__(), dedoc.data_structures.parsed_document.ParsedDocument.add_attachments(), and dedoc.data_structures.parsed_document.ParsedDocument.to_api_schema().
content
DocumentContent dedoc.api.schema.parsed_document.ParsedDocument.content = Field(description="Document text and tables") static
Referenced by dedoc.data_structures.parsed_document.ParsedDocument.__init__(), and dedoc.data_structures.parsed_document.ParsedDocument.to_api_schema().
metadata
DocumentMetadata dedoc.api.schema.parsed_document.ParsedDocument.metadata = Field(description="Document metadata such as size, creation date and so on") static
Referenced by dedoc.data_structures.line_with_meta.LineWithMeta.__getitem__(), dedoc.data_structures.parsed_document.ParsedDocument.__init__(), dedoc.data_structures.table.Table.__init__(), dedoc.data_structures.unstructured_document.UnstructuredDocument.__init__(), dedoc.data_structures.tree_node.TreeNode.__init__(), dedoc.data_structures.line_with_meta.LineWithMeta.__repr__(), dedoc.data_structures.tree_node.TreeNode.add_text(), dedoc.data_structures.parsed_document.ParsedDocument.to_api_schema(), dedoc.data_structures.table.Table.to_api_schema(), dedoc.data_structures.tree_node.TreeNode.to_api_schema(), and dedoc.readers.pdf_reader.data_classes.tables.scantable.ScanTable.uid().
version
str dedoc.api.schema.parsed_document.ParsedDocument.version = Field(description="Version of the program that parsed this document", example="0.9.1") static
warnings
List dedoc.api.schema.parsed_document.ParsedDocument.warnings = Field(description="List of warnings and possible errors, arising in the process of document parsing") static
Referenced by dedoc.data_structures.parsed_document.ParsedDocument.__init__(), dedoc.data_structures.unstructured_document.UnstructuredDocument.__init__(), dedoc.data_structures.document_content.DocumentContent.__init__(), and dedoc.data_structures.parsed_document.ParsedDocument.to_api_schema().
The documentation for this class was generated from the following file:
dedoc/api/schema/parsed_document.py