Dedoc: dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.letter_txtlayer_classifier.LetterTxtlayerClassifier Class Reference
dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.letter_txtlayer_classifier.LetterTxtlayerClassifier Class Reference
Simple multilingual textual layer correctness classification.
Public Member Functions
None __init__ (self, *dict config)
np.ndarray predict (self, List[List[LineWithMeta]] lines)
Classifies the correctness of the text layer in a PDF document.
None __init__ (self, *dict config)
np.ndarray predict (self, List[List[LineWithMeta]] lines)
Classifies the correctness of the text layer in a PDF document.
Private Attributes
__symbol_threshold
Additional Inherited Members
Public Attributes inherited from dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.abstract_txtlayer_classifier.AbstractTxtlayerClassifier
config
logger
Detailed Description
Simple multilingual textual layer correctness classification.
Textual layer is considered as correct if percent of letters in the text > 50%.
Constructor & Destructor Documentation
__init__()
None dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.letter_txtlayer_classifier.LetterTxtlayerClassifier.__init__ (self, *dict config)
Reimplemented from dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.abstract_txtlayer_classifier.AbstractTxtlayerClassifier.
References dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.letter_txtlayer_classifier.LetterTxtlayerClassifier.__init__().
Referenced by dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.letter_txtlayer_classifier.LetterTxtlayerClassifier.__init__(), and dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
predict()
np.ndarray dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.letter_txtlayer_classifier.LetterTxtlayerClassifier.predict (self, List[List[LineWithMeta]] lines)
Classifies the correctness of the text layer in a PDF document.
:param lines: list of lists with document textual lines. :returns: array of bool values - True if the textual layer is correct, False otherwise.
Reimplemented from dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.abstract_txtlayer_classifier.AbstractTxtlayerClassifier.
References dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.letter_txtlayer_classifier.LetterTxtlayerClassifier.__symbol_threshold.
Member Data Documentation
__symbol_threshold
dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.letter_txtlayer_classifier.LetterTxtlayerClassifier.__symbol_threshold private
Referenced by dedoc.readers.pdf_reader.pdf_auto_reader.txtlayer_classifier.letter_txtlayer_classifier.LetterTxtlayerClassifier.predict().
The documentation for this class was generated from the following file:
dedoc/readers/pdf_reader/pdf_auto_reader/txtlayer_classifier/letter_txtlayer_classifier.py