Dedoc: dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing Class Reference
dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing Class Reference
Public Member Functions
UnstructuredDocument postprocess (self, UnstructuredDocument document)
Private Member Functions
List[LineWithMeta] __lines_postprocessing (self, List[LineWithMeta] lines)
List[LineWithMeta] __add_newlines (self, List[LineWithMeta] lines)
List[LineWithMeta] __fix_special_symbols (self, List[LineWithMeta] lines)
replace some special symbols to common symbols, e.q.
Member Function Documentation
__add_newlines()
List[LineWithMeta] dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing.__add_newlines (self, List[LineWithMeta] lines) private
Referenced by dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing.__lines_postprocessing().
__fix_special_symbols()
List[LineWithMeta] dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing.__fix_special_symbols (self, List[LineWithMeta] lines) private
replace some special symbols to common symbols, e.q.
"\xa0" -> " "
Parameters
lines
Returns
:
Referenced by dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing.__lines_postprocessing().
__lines_postprocessing()
List[LineWithMeta] dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing.__lines_postprocessing (self, List[LineWithMeta] lines) private
References dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing.__add_newlines(), and dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing.__fix_special_symbols().
Referenced by dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing.postprocess().
postprocess()
UnstructuredDocument dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing.postprocess (self, UnstructuredDocument document)
References dedoc.readers.html_reader.html_line_postprocessing.HtmlLinePostprocessing.__lines_postprocessing().
The documentation for this class was generated from the following file:
dedoc/readers/html_reader/html_line_postprocessing.py