Dedoc: dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor Class Reference
dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor Class Reference
This class allows to extract some text formatting properties (see class Properties)
Public Member Functions
None __init__ (self, str file_path)
Properties get_properties (self, Tag xml, int level, Optional[Properties] properties=None)
xml examples: <a:pPr indent="0" lvl="0" marL="0" rtl="0" algn="l"> <a:rPr i="1" lang="ru" sz="1800"> <a:rPr baseline="30000" lang="ru" sz="1800">
Public Attributes
alignment_mapping
lvl2default_properties
Private Member Functions
None __update_properties (self, Tag xml, Properties properties)
None __update_alignment (self, Tag xml, Properties properties)
Dict[int, Properties] __get_default_properties_mapping (self, str file_path)
None __update_level_properties (self, Tag xml, Dict[int, Properties] lvl2properties)
Example: <a:lvl1pPr lvl="0" marR="0" rtl="0" algn="l"> <a:lnSpc><a:spcPct val="100000"/></a:lnSpc> <a:spcBef><a:spcPts val="0"/></a:spcBef> <a:spcAft><a:spcPts val="0"/></a:spcAft> <a:buClr><a:srgbClr val="000000"/></a:buClr> <a:buFont typeface="Arial"/> <a:defRPr b="0" i="0" sz="1400" u="none" cap="none" strike="noStrike"> <a:solidFill><a:srgbClr val="000000"/></a:solidFill> <a:latin typeface="Arial"/> <a:ea typeface="Arial"/> <a:cs typeface="Arial"/> <a:sym typeface="Arial"/> </a:defRPr> </a:lvl1pPr>
Detailed Description
This class allows to extract some text formatting properties (see class Properties)
Properties hierarchy:
Run and paragraph properties (slide.xml)
Slide layout properties (slideLayout.xml) TODO
Master slide properties (slideMaster.xml) TODO
Presentation default properties (presentation.xml -> defaultTextStyle)
Constructor & Destructor Documentation
__init__()
None dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__init__ (self, str file_path)
Referenced by dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
__get_default_properties_mapping()
Dict[int, Properties] dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__get_default_properties_mapping (self, str file_path) private
References dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_level_properties().
__update_alignment()
None dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_alignment (self, Tag xml, Properties properties) private
References dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.alignment_mapping.
Referenced by dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_level_properties(), and dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_properties().
__update_level_properties()
None dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_level_properties (self, Tag xml, Dict[int, Properties] lvl2properties) private
Example: <a:lvl1pPr lvl="0" marR="0" rtl="0" algn="l"> <a:lnSpc><a:spcPct val="100000"/></a:lnSpc> <a:spcBef><a:spcPts val="0"/></a:spcBef> <a:spcAft><a:spcPts val="0"/></a:spcAft> <a:buClr><a:srgbClr val="000000"/></a:buClr> <a:buFont typeface="Arial"/> <a:defRPr b="0" i="0" sz="1400" u="none" cap="none" strike="noStrike"> <a:solidFill><a:srgbClr val="000000"/></a:solidFill> <a:latin typeface="Arial"/> <a:ea typeface="Arial"/> <a:cs typeface="Arial"/> <a:sym typeface="Arial"/> </a:defRPr> </a:lvl1pPr>
References dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_alignment(), and dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_properties().
Referenced by dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__get_default_properties_mapping().
__update_properties()
None dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_properties (self, Tag xml, Properties properties) private
References dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_alignment().
Referenced by dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_level_properties(), and dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.get_properties().
get_properties()
Properties dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.get_properties (self, Tag xml, int level, Optional[Properties] properties = None)
xml examples: <a:pPr indent="0" lvl="0" marL="0" rtl="0" algn="l"> <a:rPr i="1" lang="ru" sz="1800"> <a:rPr baseline="30000" lang="ru" sz="1800">
References dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_properties(), and dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.lvl2default_properties.
Member Data Documentation
alignment_mapping
dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.alignment_mapping
Referenced by dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.__update_alignment().
lvl2default_properties
dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.lvl2default_properties
Referenced by dedoc.readers.pptx_reader.properties_extractor.PropertiesExtractor.get_properties().
The documentation for this class was generated from the following file:
dedoc/readers/pptx_reader/properties_extractor.py