Dedoc: dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition Class Reference
dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition Class Reference
\par \b Purpose\/ \: Route a document to the correct structure constructor based on the structure_type parameter, enabling runtime selection of document structure representations.
Public Member Functions
None __init__ (self, Dict[str, AbstractStructureConstructor] constructors, AbstractStructureConstructor default_constructor)
\par \b Purpose\/ \: Initialize the composition with a registry of named constructors and a fallback default constructor.
ParsedDocument construct (self, UnstructuredDocument document, Optional[dict] parameters=None)
\par \b Purpose\/ \: Dispatch the document to the matching constructor by structure_type; raise StructureExtractorError if the type is unknown.
ParsedDocument construct (self, UnstructuredDocument document, Optional[dict] parameters=None)
\par \b Purpose\/ \: Transform an intermediate UnstructuredDocument into a final ParsedDocument by applying the specific structure construction algorithm.
Public Attributes
constructors
default_constructor
Detailed Description
\par \b Purpose\/ \: Route a document to the correct structure constructor based on the structure_type parameter, enabling runtime selection of document structure representations.
This class allows to construct structure from any document according to the available list of structure constructors. The list of structure constructors and names of structure types for them is set via the class constructor. Each structure type defines some specific document representation, which is retrieved via the corresponding structure constructor.
Constructor & Destructor Documentation
__init__()
None dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition.__init__ (self, Dict[str, AbstractStructureConstructor] constructors, AbstractStructureConstructor default_constructor)
\par \b Purpose\/ \: Initialize the composition with a registry of named constructors and a fallback default constructor.
\par \b I/O\/ \: Dict[str, AbstractStructureConstructor], AbstractStructureConstructor -> None \par \b Complexity\/ \: 2
:param constructors: mapping structure_type -> structure constructor, defined for certain structure representations :param default_constructor: the structure constructor, that will be used by default if the empty structure type is given
Referenced by dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
construct()
ParsedDocument dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition.construct (self, UnstructuredDocument document, Optional[dict] parameters = None)
\par \b Purpose\/ \: Dispatch the document to the matching constructor by structure_type; raise StructureExtractorError if the type is unknown.
\par \b Uses\/ \: AbstractStructureConstructor, StructureExtractorError \par \b I/O\/ \: UnstructuredDocument, Optional[dict] -> ParsedDocument \par \b Complexity\/ \: 5
Construct the result document structure according to the structure_type parameter. If structure_type is empty string or None the default constructor will be used. To get the information about the parameters look at the documentation of :class:~dedoc.structure_constructors.AbstractStructureConstructor.
Reimplemented from dedoc.structure_constructors.abstract_structure_constructor.AbstractStructureConstructor.
References dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition.construct(), dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition.constructors, and dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition.default_constructor.
Referenced by dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition.construct().
Member Data Documentation
constructors
dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition.constructors
Referenced by dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition.construct().
default_constructor
dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition.default_constructor
Referenced by dedoc.structure_constructors.structure_constructor_composition.StructureConstructorComposition.construct().
The documentation for this class was generated from the following file:
dedoc/structure_constructors/structure_constructor_composition.py