Dedoc: dedoc.attachments_extractors.concrete_attachments_extractors.pptx_attachments_extractor.PptxAttachmentsExtractor Class Reference
dedoc.attachments_extractors.concrete_attachments_extractors.pptx_attachments_extractor.PptxAttachmentsExtractor Class Reference
\par \b Purpose\/ \: Extract embedded files (images, OLE objects) from PowerPoint .pptx archives.
Public Member Functions
None __init__ (self, *Optional[dict] config=None)
\par \b Purpose\/ \: Initialize the pptx extractor with recognized pptx-like file extensions and MIME types.
List[AttachedFile] extract (self, str file_path, Optional[dict] parameters=None)
\par \b Purpose\/ \: Extract all attachments from the given .pptx file by delegating to the generic Office-format extraction with attachments_dir="ppt".
None __init__ (self, *Optional[dict] config=None, Optional[Set[str]] recognized_extensions=None, Optional[Set[str]] recognized_mimes=None)
\par \b Purpose\/ \: Initialize with config and recognized extensions/mimes, delegating to the parent AbstractAttachmentsExtractor.
Public Member Functions inherited from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor
None __init__ (self, *Optional[dict] config=None, Optional[Set[str]] recognized_extensions=None, Optional[Set[str]] recognized_mimes=None)
\par \b Purpose\/ \: Initialize the extractor with configuration, recognized file extensions, and recognized MIME types.
bool can_extract (self, Optional[str] file_path=None, Optional[str] extension=None, Optional[str] mime=None, Optional[dict] parameters=None)
\par \b Purpose\/ \: Determine whether this extractor can handle the given file based on its extension or MIME type.
List[AttachedFile] extract (self, str file_path, Optional[dict] parameters=None)
\par \b Purpose\/ \: Abstract method: extract attachments from the given file.
Additional Inherited Members
Static Public Member Functions inherited from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor
bool with_attachments (dict parameters)
\par \b Purpose\/ \: Static helper: check if the 'with_attachments' parameter is truthy.
Public Attributes inherited from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor
config
logger
Protected Member Functions inherited from dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor
List[AttachedFile] _get_attachments (self, str tmpdir, str filename, dict parameters, str attachments_dir)
\par \b Purpose\/ \: Extract all attachments from an Office-format ZIP archive: collect media/embeddings from the specified folder, parse .bin OLE files for embedded PDF or Ole10Native content.
Protected Member Functions inherited from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor
List[AttachedFile] _content2attach_file (self, List[Tuple[str, bytes]] content, str tmpdir, bool need_content_analysis, dict parameters)
\par \b Purpose\/ \: Convert a list of (filename, binary_data) tuples into a list of AttachedFile objects, saving binary data to unique files on disk.
Protected Attributes inherited from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor
_recognized_extensions
_recognized_mimes
Detailed Description
\par \b Purpose\/ \: Extract embedded files (images, OLE objects) from PowerPoint .pptx archives.
Constructor & Destructor Documentation
__init__()
None dedoc.attachments_extractors.concrete_attachments_extractors.pptx_attachments_extractor.PptxAttachmentsExtractor.__init__ (self, *Optional[dict] config = None)
\par \b Purpose\/ \: Initialize the pptx extractor with recognized pptx-like file extensions and MIME types.
\par \b Uses\/ \: dedoc.extensions.recognized_extensions, dedoc.extensions.recognized_mimes \par \b I/O\/ \: Optional[dict] -> None \par \b Complexity\/ \: 2
Reimplemented from dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor.
References dedoc.attachments_extractors.concrete_attachments_extractors.pptx_attachments_extractor.PptxAttachmentsExtractor.__init__().
Referenced by dedoc.attachments_extractors.concrete_attachments_extractors.pptx_attachments_extractor.PptxAttachmentsExtractor.__init__(), and dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
extract()
List[AttachedFile] dedoc.attachments_extractors.concrete_attachments_extractors.pptx_attachments_extractor.PptxAttachmentsExtractor.extract (self, str file_path, Optional[dict] parameters = None)
\par \b Purpose\/ \: Extract all attachments from the given .pptx file by delegating to the generic Office-format extraction with attachments_dir="ppt".
\par \b Uses\/ \: AbstractOfficeAttachmentsExtractor._get_attachments \par \b I/O\/ \: str, Optional[dict] -> List[AttachedFile] \par \b Complexity\/ \: 3
Reimplemented from dedoc.attachments_extractors.abstract_attachment_extractor.AbstractAttachmentsExtractor.
References dedoc.attachments_extractors.concrete_attachments_extractors.abstract_office_attachments_extractor.AbstractOfficeAttachmentsExtractor._get_attachments().
The documentation for this class was generated from the following file:
dedoc/attachments_extractors/concrete_attachments_extractors/pptx_attachments_extractor.py