Dedoc: dedoc.api.api_args.QueryParameters Class Reference
dedoc.api.api_args.QueryParameters Class Reference
\par \b Purpose\/ \: Capture all dedoc API query parameters from multipart form data with enum-validated defaults for document parsing configuration.
Public Member Functions
dict to_dict (self)
\par \b Purpose\/ \: Convert the QueryParameters dataclass to a flat dict with defaults resolved for downstream pipeline configuration.
Static Public Attributes
str document_type = Form("", enum=["", "law", "tz", "diploma", "article", "fintoc"], description="Document domain")
str patterns = Form("", description='Patterns for default document type (when document_type="")')
str structure_type = Form("tree", enum=["linear", "tree"], description="Output structure type")
str return_format
str with_attachments = Form("false", enum=["true", "false"], description="Enable attached files extraction")
str need_content_analysis = Form("false", enum=["true", "false"], description="Enable parsing contents of the attached files")
str recursion_deep_attachments = Form("10", description="Depth on which nested attachments will be parsed if need_content_analysis=true")
str return_base64 = Form("false", enum=["true", "false"], description="Save attached images to the document metadata in base64 format")
str need_pdf_table_analysis = Form("true", enum=["true", "false"], description="Enable table recognition for pdf")
str table_type = Form("", description="Pipeline mode for table recognition")
str pdf_with_text_layer
str textual_layer_classifier = Form("ml", enum=["ml", "simple", "letter"], description="Type of classifier for PDF textual layer detection")
str each_page_textual_layer_detection = Form("false", enum=["true", "false"], description="Detect textual layer on each page. Slower but more accurate.")
str language = Form("rus+eng", description="Recognition language ('rus+eng', 'rus', 'eng', 'fra', 'spa')")
str pages = Form(":", description='Page numbers range for reading PDF or images, "left:right" means read pages from left to right')
str is_one_column_document
str document_orientation
str need_header_footer_analysis = Form("false", enum=["true", "false"], description="Exclude headers and footers from PDF parsing result")
str need_binarization = Form("false", enum=["true", "false"], description="Binarize document pages (for images or PDF without a textual layer)")
str need_gost_frame_analysis = Form("false", enum=["true", "false"], description="Parameter for detecting and ignoring GOST frame of the document")
Optional delimiter = Form(None, description="Column separator for CSV files")
Optional encoding = Form(None, description="Document encoding")
str html_fields = Form("", description="List of fields for JSON documents to be parsed as HTML documents")
str handle_invisible_table = Form("false", enum=["true", "false"], description="Handle tables without visible borders as tables in HTML")
Detailed Description
\par \b Purpose\/ \: Capture all dedoc API query parameters from multipart form data with enum-validated defaults for document parsing configuration.
\par \b I/O\/ \: FastAPI Form(...) fields -> QueryParameters instance
Member Function Documentation
to_dict()
dict dedoc.api.api_args.QueryParameters.to_dict (self)
\par \b Purpose\/ \: Convert the QueryParameters dataclass to a flat dict with defaults resolved for downstream pipeline configuration.
\par \b Uses\/ \: dataclasses.asdict \par \b I/O\/ \: None -> dict \par \b Complexity\/ \: 3
Member Data Documentation
delimiter
Optional dedoc.api.api_args.QueryParameters.delimiter = Form(None, description="Column separator for CSV files") static
document_orientation
str dedoc.api.api_args.QueryParameters.document_orientation static
Initial value:
=  Form("auto", enum=["auto", "no_change"],
                                     description='Orientation of the document pages, "auto" - predict orientation (0, 90, 180, 270 degrees), '
                                                 '"no_change" - set vertical orientation of the document without using an orientation classifier')
document_type
str dedoc.api.api_args.QueryParameters.document_type = Form("", enum=["", "law", "tz", "diploma", "article", "fintoc"], description="Document domain") static
each_page_textual_layer_detection
str dedoc.api.api_args.QueryParameters.each_page_textual_layer_detection = Form("false", enum=["true", "false"], description="Detect textual layer on each page. Slower but more accurate.") static
encoding
Optional dedoc.api.api_args.QueryParameters.encoding = Form(None, description="Document encoding") static
handle_invisible_table
str dedoc.api.api_args.QueryParameters.handle_invisible_table = Form("false", enum=["true", "false"], description="Handle tables without visible borders as tables in HTML") static
html_fields
str dedoc.api.api_args.QueryParameters.html_fields = Form("", description="List of fields for JSON documents to be parsed as HTML documents") static
is_one_column_document
str dedoc.api.api_args.QueryParameters.is_one_column_document static
Initial value:
=  Form("auto", enum=["auto", "true", "false"],
                                       description='One or multiple column document, "auto" - predict number of page columns automatically')
language
str dedoc.api.api_args.QueryParameters.language = Form("rus+eng", description="Recognition language ('rus+eng', 'rus', 'eng', 'fra', 'spa')") static
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_extractors.concrete_extractors.onepage_table_extractor.OnePageTableExtractor.extract_onepage_tables_from_image(), and dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_extractors.concrete_extractors.onepage_table_extractor.OnePageTableExtractor.handle_cells().
need_binarization
str dedoc.api.api_args.QueryParameters.need_binarization = Form("false", enum=["true", "false"], description="Binarize document pages (for images or PDF without a textual layer)") static
need_content_analysis
str dedoc.api.api_args.QueryParameters.need_content_analysis = Form("false", enum=["true", "false"], description="Enable parsing contents of the attached files") static
Referenced by dedoc.data_structures.attached_file.AttachedFile.__init__().
need_gost_frame_analysis
str dedoc.api.api_args.QueryParameters.need_gost_frame_analysis = Form("false", enum=["true", "false"], description="Parameter for detecting and ignoring GOST frame of the document") static
need_header_footer_analysis
str dedoc.api.api_args.QueryParameters.need_header_footer_analysis = Form("false", enum=["true", "false"], description="Exclude headers and footers from PDF parsing result") static
need_pdf_table_analysis
str dedoc.api.api_args.QueryParameters.need_pdf_table_analysis = Form("true", enum=["true", "false"], description="Enable table recognition for pdf") static
pages
str dedoc.api.api_args.QueryParameters.pages = Form(":", description='Page numbers range for reading PDF or images, "left:right" means read pages from left to right') static
patterns
str dedoc.api.api_args.QueryParameters.patterns = Form("", description='Patterns for default document type (when document_type="")') static
Referenced by dedoc.structure_extractors.patterns.pattern_composition.PatternComposition.get_hierarchy_level().
pdf_with_text_layer
str dedoc.api.api_args.QueryParameters.pdf_with_text_layer static
Initial value:
=  Form("auto_tabby", enum=["true", "false", "auto", "auto_tabby", "tabby", "bad_encoding"],
                                    description="Extract text from a text layer of PDF or using OCR methods for image-like documents")
recursion_deep_attachments
str dedoc.api.api_args.QueryParameters.recursion_deep_attachments = Form("10", description="Depth on which nested attachments will be parsed if need_content_analysis=true") static
return_base64
str dedoc.api.api_args.QueryParameters.return_base64 = Form("false", enum=["true", "false"], description="Save attached images to the document metadata in base64 format") static
return_format
str dedoc.api.api_args.QueryParameters.return_format static
Initial value:
=  Form("json", enum=["json", "html", "plain_text", "tree", "collapsed_tree", "ujson", "pretty_json"],
                              description="Response representation, most types (except json) are used for debug purposes only")
structure_type
str dedoc.api.api_args.QueryParameters.structure_type = Form("tree", enum=["linear", "tree"], description="Output structure type") static
table_type
str dedoc.api.api_args.QueryParameters.table_type = Form("", description="Pipeline mode for table recognition") static
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_recognizer.TableRecognizer.__rec_tables_from_img().
textual_layer_classifier
str dedoc.api.api_args.QueryParameters.textual_layer_classifier = Form("ml", enum=["ml", "simple", "letter"], description="Type of classifier for PDF textual layer detection") static
with_attachments
str dedoc.api.api_args.QueryParameters.with_attachments = Form("false", enum=["true", "false"], description="Enable attached files extraction") static
The documentation for this class was generated from the following file:
dedoc/api/api_args.py