Dedoc: dedoc.api.schema.document_metadata.DocumentMetadata Class Reference
dedoc.api.schema.document_metadata.DocumentMetadata Class Reference
\par \b Purpose\/ \: Hold document file metadata (name, size, timestamps, MIME type) with open extension for format-specific attributes via Extra.allow.
Classes
class Config
Static Public Attributes
str
description
example
str file_name = Field(description="Original document name before rename and conversion", example="example.odt")
str temporary_file_name = Field(description="File name during parsing (unique name after rename and conversion)", example="123.odt")
int size = Field(description="File size in bytes", example=20060)
int modified_time = Field(description="Modification time of the document in the UnixTime format", example=1590579805)
int created_time = Field(description="Creation time of the document in the UnixTime format", example=1590579805)
int access_time = Field(description="File access time in the UnixTime format", example=1590579805)
str file_type = Field(description="Mime type of the file", example="application/vnd.oasis.opendocument.text")
Detailed Description
\par \b Purpose\/ \: Hold document file metadata (name, size, timestamps, MIME type) with open extension for format-specific attributes via Extra.allow.
\par \b I/O\/ \: (uid, file_name, size, timestamps, file_type, **extra) -> JSON serializable model
Document metadata like its name, size, author, etc.
:ivar file_name: original document name (before rename and conversion, so it can contain non-ascii symbols, spaces and so on) :ivar temporary_file_name: file name during parsing (unique name after rename and conversion) :ivar size: size of the original file in bytes :ivar modified_time: time of the last modification in unix time format (seconds since the epoch) :ivar created_time: time of the creation in unixtime :ivar access_time: time of the last access to the file in unixtime :ivar file_type: mime type of the file :ivar uid: document unique identifier (useful for attached files)
:vartype file_name: str :vartype temporary_file_name: str :vartype size: int :vartype modified_time: int :vartype created_time: int :vartype access_time: int :vartype file_type: str :vartype uid: str
Additional variables may be added with other file metadata.
Member Data Documentation
access_time
int dedoc.api.schema.document_metadata.DocumentMetadata.access_time = Field(description="File access time in the UnixTime format", example=1590579805) static
Referenced by dedoc.data_structures.document_metadata.DocumentMetadata.__init__().
created_time
int dedoc.api.schema.document_metadata.DocumentMetadata.created_time = Field(description="Creation time of the document in the UnixTime format", example=1590579805) static
Referenced by dedoc.data_structures.document_metadata.DocumentMetadata.__init__().
description
dedoc.api.schema.document_metadata.DocumentMetadata.description static
example
dedoc.api.schema.document_metadata.DocumentMetadata.example static
file_name
str dedoc.api.schema.document_metadata.DocumentMetadata.file_name = Field(description="Original document name before rename and conversion", example="example.odt") static
Referenced by dedoc.data_structures.document_metadata.DocumentMetadata.__init__().
file_type
str dedoc.api.schema.document_metadata.DocumentMetadata.file_type = Field(description="Mime type of the file", example="application/vnd.oasis.opendocument.text") static
Referenced by dedoc.data_structures.document_metadata.DocumentMetadata.__init__().
modified_time
int dedoc.api.schema.document_metadata.DocumentMetadata.modified_time = Field(description="Modification time of the document in the UnixTime format", example=1590579805) static
Referenced by dedoc.data_structures.document_metadata.DocumentMetadata.__init__().
size
int dedoc.api.schema.document_metadata.DocumentMetadata.size = Field(description="File size in bytes", example=20060) static
Referenced by dedoc.readers.docx_reader.data_structures.run.Run.__eq__(), and dedoc.data_structures.document_metadata.DocumentMetadata.__init__().
str
dedoc.api.schema.document_metadata.DocumentMetadata.str static
temporary_file_name
str dedoc.api.schema.document_metadata.DocumentMetadata.temporary_file_name = Field(description="File name during parsing (unique name after rename and conversion)", example="123.odt") static
Referenced by dedoc.data_structures.document_metadata.DocumentMetadata.__init__().
The documentation for this class was generated from the following file:
dedoc/api/schema/document_metadata.py