Dedoc: dedoc.api.schema.cell_with_meta.CellWithMeta Class Reference
dedoc.api.schema.cell_with_meta.CellWithMeta Class Reference
\par \b Purpose\/ \: Represent a single table cell with its text lines and HTML-like spanning properties for correct table rendering.
Static Public Attributes
List lines = Field(description="Textual lines of the cell with annotations")
int rowspan = Field(description="Number of rows to span like in HTML format", example=1)
int colspan = Field(description="Number of columns to span like in HTML format", example=2)
bool invisible = Field(description="Indicator for displaying or hiding cell text", example=False)
Detailed Description
\par \b Purpose\/ \: Represent a single table cell with its text lines and HTML-like spanning properties for correct table rendering.
\par \b I/O\/ \: (lines, rowspan, colspan, invisible) -> JSON serializable model
Holds the information about the cell: list of lines and cell properties (rowspan, colspan, invisible).
:ivar lines: list of textual lines of the cell :ivar colspan: number of columns to span (for cells merged horizontally) :ivar rowspan: number of rows to span (for cells merged vertically) :ivar invisible: indicator for displaying or hiding cell text - cells that are merged with others are hidden (for HTML display)
:vartype lines: List[LineWithMeta] :vartype colspan: int :vartype rowspan: int :vartype invisible: bool
Member Data Documentation
colspan
int dedoc.api.schema.cell_with_meta.CellWithMeta.colspan = Field(description="Number of columns to span like in HTML format", example=2) static
Referenced by dedoc.data_structures.cell_with_meta.CellWithMeta.__init__(), and dedoc.data_structures.cell_with_meta.CellWithMeta.to_api_schema().
invisible
bool dedoc.api.schema.cell_with_meta.CellWithMeta.invisible = Field(description="Indicator for displaying or hiding cell text", example=False) static
Referenced by dedoc.data_structures.cell_with_meta.CellWithMeta.__init__(), and dedoc.data_structures.cell_with_meta.CellWithMeta.to_api_schema().
lines
List dedoc.api.schema.cell_with_meta.CellWithMeta.lines = Field(description="Textual lines of the cell with annotations") static
Referenced by dedoc.data_structures.unstructured_document.UnstructuredDocument.__init__(), dedoc.data_structures.cell_with_meta.CellWithMeta.__init__(), dedoc.data_structures.cell_with_meta.CellWithMeta.get_annotations(), dedoc.data_structures.cell_with_meta.CellWithMeta.get_text(), dedoc.data_structures.unstructured_document.UnstructuredDocument.get_text(), dedoc.readers.pdf_reader.data_classes.tables.table_tree.TableTree.get_text(), dedoc.readers.pdf_reader.data_classes.tables.cell.Cell.shift(), dedoc.readers.pdf_reader.pdf_image_reader.ocr.ocr_page.ocr_paragraph.OcrParagraph.text(), and dedoc.data_structures.cell_with_meta.CellWithMeta.to_api_schema().
rowspan
int dedoc.api.schema.cell_with_meta.CellWithMeta.rowspan = Field(description="Number of rows to span like in HTML format", example=1) static
Referenced by dedoc.data_structures.cell_with_meta.CellWithMeta.__init__(), and dedoc.data_structures.cell_with_meta.CellWithMeta.to_api_schema().
The documentation for this class was generated from the following file:
dedoc/api/schema/cell_with_meta.py