Dedoc: dedoc.data_structures.hierarchy_level.HierarchyLevel Class Reference
dedoc.data_structures.hierarchy_level.HierarchyLevel Class Reference
\par \b Purpose\/ \: Define the hierarchical level of a document line — encodes primary (level_1) and secondary (level_2) importance with line type.
Public Member Functions
None __init__ (self, Optional[int] level_1, Optional[int] level_2, bool can_be_multiline, str line_type)
\par \b Purpose\/ \: Initialize hierarchy level with validated level_1, level_2, multiline flag, and line type.
bool __eq__ (self, "HierarchyLevel" other)
\par \b Purpose\/ \: Compare two hierarchy levels — None values are treated as +inf for equality.
bool __lt__ (self, "HierarchyLevel" other)
\par \b Purpose\/ \: Compare two hierarchy levels for ordering — lower level_1/level_2 means more important.
str __str__ (self)
\par \b Purpose\/ \: Return string representation of the hierarchy level.
bool is_raw_text (self)
\par \b Purpose\/ \: Check if the line is raw text.
bool is_unknown (self)
\par \b Purpose\/ \: Check if the line type is unknown (only for levels from readers).
bool is_list_item (self)
\par \b Purpose\/ \: Check if the line is a list item.
Static Public Member Functions
"HierarchyLevel" create_raw_text ()
\par \b Purpose\/ \: Create hierarchy level for a raw textual line (both levels None).
"HierarchyLevel" create_unknown ()
\par \b Purpose\/ \: Create hierarchy level for a line with unknown type.
"HierarchyLevel" create_root ()
\par \b Purpose\/ \: Create hierarchy level for the document root (level_1=0, level_2=0).
Public Attributes
level_1
level_2
line_type
Static Public Attributes
str root = "root"
str toc = "toc"
str header = "header"
str toc_item = "toc_item"
str list = "list"
str list_item = "list_item"
str bullet_list_item = "bullet_list_item"
str raw_text = "raw_text"
str footer = "footer"
str page_id = "page_id"
str unknown = "unknown"
Private Member Functions
bool __is_defined (self, "HierarchyLevel" other)
\par \b Purpose\/ \: Check if both self and other have defined (non-None) level_1 and level_2.
int __to_number (self, Optional[int] x)
\par \b Purpose\/ \: Convert Optional[int] to number, mapping None to +inf for comparison purposes.
Detailed Description
\par \b Purpose\/ \: Define the hierarchical level of a document line — encodes primary (level_1) and secondary (level_2) importance with line type.
This class defines the level of the document line. The lower is its value, the more important the line is.
The level of the line consists of two parts:
level_1 defines primary importance (e.g. root - level_1=0, header - level_1=1, etc.);
level_2 defines the level inside lines of equal type (e.g. for list items - "1." - level_2=1, "1.1." - level_2=2, etc.).
For the least important lines (line_type=raw_text) both levels are None.
Look to the :ref:hierarchy level description <add_structure_type_hierarchy_level> to get more details.
:ivar level_1: value of a line's primary importance :ivar level_2: level of the line inside specific class :ivar can_be_multiline: is used to unify lines inside tree node, if line can be multiline, it can be joined with another line :ivar line_type: type of the line, e.g. raw text, list item, header, etc.
:vartype level_1: Optional[int] :vartype level_2: Optional[int] :vartype can_be_multiline: bool :vartype line_type: str
Constructor & Destructor Documentation
__init__()
None dedoc.data_structures.hierarchy_level.HierarchyLevel.__init__ (self, Optional[int] level_1, Optional[int] level_2, bool can_be_multiline, str line_type)
\par \b Purpose\/ \: Initialize hierarchy level with validated level_1, level_2, multiline flag, and line type.
\par \b I/O\/ \: (Optional[int], Optional[int], bool, str) -> None \par \b Complexity\/ \: 3
:param level_1: value of a line's primary importance :param level_2: level of the line inside specific class :param can_be_multiline: is used to unify lines inside tree node, if line can be multiline, it can be joined with another line :param line_type: type of the line
References dedoc.data_structures.hierarchy_level.HierarchyLevel.level_1, dedoc.data_structures.hierarchy_level.HierarchyLevel.level_2, and dedoc.data_structures.hierarchy_level.HierarchyLevel.line_type.
Referenced by dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
__eq__()
bool dedoc.data_structures.hierarchy_level.HierarchyLevel.__eq__ (self, "HierarchyLevel" other)
\par \b Purpose\/ \: Compare two hierarchy levels — None values are treated as +inf for equality.
\par \b Uses\/ \: __to_number \par \b I/O\/ \: (HierarchyLevel) -> bool \par \b Complexity\/ \: 3
Defines the equality of two hierarchy levels:
two lines with equal level_1, level_2 are equal.
if some of the levels is None, its value is considered as +inf (infinities have equal value)
:param other: other hierarchy level :return: whether current hierarchy level == other hierarchy level
References dedoc.data_structures.hierarchy_level.HierarchyLevel.__to_number(), dedoc.data_structures.hierarchy_level.HierarchyLevel.level_1, and dedoc.data_structures.hierarchy_level.HierarchyLevel.level_2.
__is_defined()
bool dedoc.data_structures.hierarchy_level.HierarchyLevel.__is_defined (self, "HierarchyLevel" other) private
\par \b Purpose\/ \: Check if both self and other have defined (non-None) level_1 and level_2.
\par \b I/O\/ \: (HierarchyLevel) -> bool \par \b Complexity\/ \: 2
References dedoc.data_structures.hierarchy_level.HierarchyLevel.level_1, and dedoc.data_structures.hierarchy_level.HierarchyLevel.level_2.
Referenced by dedoc.data_structures.hierarchy_level.HierarchyLevel.__lt__().
__lt__()
bool dedoc.data_structures.hierarchy_level.HierarchyLevel.__lt__ (self, "HierarchyLevel" other)
\par \b Purpose\/ \: Compare two hierarchy levels for ordering — lower level_1/level_2 means more important.
\par \b Uses\/ \: __is_defined, __to_number \par \b I/O\/ \: (HierarchyLevel) -> bool \par \b Complexity\/ \: 5
Defines the comparison of hierarchy levels:
current level < other level if (level_1, level_2) < other (level_1, level_2);
if some of the levels is None, its value is considered as +inf (infinities have equal value)
:param other: other hierarchy level :return: whether current hierarchy level < other hierarchy level
References dedoc.data_structures.hierarchy_level.HierarchyLevel.__is_defined().
__str__()
str dedoc.data_structures.hierarchy_level.HierarchyLevel.__str__ (self)
\par \b Purpose\/ \: Return string representation of the hierarchy level.
\par \b I/O\/ \: None -> str \par \b Complexity\/ \: 1
Referenced by dedoc.data_structures.annotation.Annotation.__repr__(), dedoc.readers.pdf_reader.data_classes.tables.cell.Cell.__repr__(), dedoc.readers.pdf_reader.data_classes.text_with_bbox.TextWithBBox.__repr__(), dedoc.readers.pdf_reader.data_classes.word_with_bbox.WordWithBBox.__repr__(), and dedoc.structure_extractors.feature_extractors.list_features.prefix.prefix.LinePrefix.__repr__().
__to_number()
int dedoc.data_structures.hierarchy_level.HierarchyLevel.__to_number (self, Optional[int] x) private
\par \b Purpose\/ \: Convert Optional[int] to number, mapping None to +inf for comparison purposes.
\par \b Uses\/ \: numpy \par \b I/O\/ \: Optional[int] -> int \par \b Complexity\/ \: 2
Referenced by dedoc.data_structures.hierarchy_level.HierarchyLevel.__eq__().
create_raw_text()
"HierarchyLevel" dedoc.data_structures.hierarchy_level.HierarchyLevel.create_raw_text () static
\par \b Purpose\/ \: Create hierarchy level for a raw textual line (both levels None).
\par \b I/O\/ \: None -> HierarchyLevel \par \b Complexity\/ \: 1
Create hierarchy level for a raw textual line.
create_root()
"HierarchyLevel" dedoc.data_structures.hierarchy_level.HierarchyLevel.create_root () static
\par \b Purpose\/ \: Create hierarchy level for the document root (level_1=0, level_2=0).
\par \b I/O\/ \: None -> HierarchyLevel \par \b Complexity\/ \: 1
Create hierarchy level for the document root.
create_unknown()
"HierarchyLevel" dedoc.data_structures.hierarchy_level.HierarchyLevel.create_unknown () static
\par \b Purpose\/ \: Create hierarchy level for a line with unknown type.
\par \b I/O\/ \: None -> HierarchyLevel \par \b Complexity\/ \: 1
Create hierarchy level for a line with unknown type.
is_list_item()
bool dedoc.data_structures.hierarchy_level.HierarchyLevel.is_list_item (self)
\par \b Purpose\/ \: Check if the line is a list item.
\par \b I/O\/ \: None -> bool \par \b Complexity\/ \: 1
Check if the line is a list item.
References dedoc.data_structures.hierarchy_level.HierarchyLevel.line_type.
is_raw_text()
bool dedoc.data_structures.hierarchy_level.HierarchyLevel.is_raw_text (self)
\par \b Purpose\/ \: Check if the line is raw text.
\par \b I/O\/ \: None -> bool \par \b Complexity\/ \: 1
Check if the line is raw text.
is_unknown()
bool dedoc.data_structures.hierarchy_level.HierarchyLevel.is_unknown (self)
\par \b Purpose\/ \: Check if the line type is unknown (only for levels from readers).
\par \b I/O\/ \: None -> bool \par \b Complexity\/ \: 1
Check if the type of the line is unknown (only for levels from readers).
References dedoc.data_structures.hierarchy_level.HierarchyLevel.line_type.
Member Data Documentation
bullet_list_item
str dedoc.data_structures.hierarchy_level.HierarchyLevel.bullet_list_item = "bullet_list_item" static
footer
str dedoc.data_structures.hierarchy_level.HierarchyLevel.footer = "footer" static
header
str dedoc.data_structures.hierarchy_level.HierarchyLevel.header = "header" static
level_1
dedoc.data_structures.hierarchy_level.HierarchyLevel.level_1
Referenced by dedoc.data_structures.hierarchy_level.HierarchyLevel.__eq__(), dedoc.data_structures.hierarchy_level.HierarchyLevel.__init__(), and dedoc.data_structures.hierarchy_level.HierarchyLevel.__is_defined().
level_2
dedoc.data_structures.hierarchy_level.HierarchyLevel.level_2
Referenced by dedoc.data_structures.hierarchy_level.HierarchyLevel.__eq__(), dedoc.data_structures.hierarchy_level.HierarchyLevel.__init__(), and dedoc.data_structures.hierarchy_level.HierarchyLevel.__is_defined().
line_type
dedoc.data_structures.hierarchy_level.HierarchyLevel.line_type
Referenced by dedoc.data_structures.hierarchy_level.HierarchyLevel.__init__(), dedoc.data_structures.hierarchy_level.HierarchyLevel.is_list_item(), and dedoc.data_structures.hierarchy_level.HierarchyLevel.is_unknown().
list
str dedoc.data_structures.hierarchy_level.HierarchyLevel.list = "list" static
list_item
str dedoc.data_structures.hierarchy_level.HierarchyLevel.list_item = "list_item" static
page_id
str dedoc.data_structures.hierarchy_level.HierarchyLevel.page_id = "page_id" static
Referenced by dedoc.data_structures.line_metadata.LineMetadata.__init__(), dedoc.data_structures.table_metadata.TableMetadata.__init__(), dedoc.readers.pptx_reader.shape.PptxShape.get_lines(), dedoc.data_structures.line_metadata.LineMetadata.to_api_schema(), dedoc.data_structures.table_metadata.TableMetadata.to_api_schema(), and dedoc.readers.pptx_reader.table.PptxTable.to_table().
raw_text
str dedoc.data_structures.hierarchy_level.HierarchyLevel.raw_text = "raw_text" static
root
str dedoc.data_structures.hierarchy_level.HierarchyLevel.root = "root" static
toc
str dedoc.data_structures.hierarchy_level.HierarchyLevel.toc = "toc" static
toc_item
str dedoc.data_structures.hierarchy_level.HierarchyLevel.toc_item = "toc_item" static
unknown
str dedoc.data_structures.hierarchy_level.HierarchyLevel.unknown = "unknown" static
The documentation for this class was generated from the following file:
dedoc/data_structures/hierarchy_level.py