Dedoc: dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter Class Reference
dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter Class Reference
split merged cells, change table into rectangular
Public Member Functions
None __init__ (self, float eps=0.5)
List[List[Cell]] split (self, List[List[Cell]] cells)
split merged cells
Public Attributes
eps
Protected Member Functions
List[List[Cell]] _merge_close_borders (self, List[List[Cell]] cells)
merge close borders into one border
Static Private Member Functions
None __split_one_cell (Cell cell, np.ndarray horizontal_borders, np.ndarray vertical_borders, List[List[Cell]] result_matrix)
np.ndarray __sort_unique (List[int] borders)
Dict[int, int] __get_border_dict (List[int] borders, float threshold)
Tuple[List[int], List[int]] __get_borders (List[List[Cell]] cells)
Detailed Description
split merged cells, change table into rectangular
(0, 0) ---------------------------------------—> x | ____________________________________________ ____________________________________________ | | | B | | A | A | B | | | A |___________________| |_________|____________|___________________| | | | C | | A | A | C | | |______________________|___________________| -> |_________|____________|___________________| | | D | E | F | | D | E | F | | |_________|____________|___________________| |_________|____________|___________________| | | G | | G | G | G | | |__________________________________________| |_________|____________|___________________| | V y
Constructor & Destructor Documentation
__init__()
None dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.__init__ (self, float eps = 0.5)
Referenced by dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
__get_border_dict()
Dict[int, int] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.__get_border_dict (List[int] borders, float threshold) static private
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter._merge_close_borders().
__get_borders()
Tuple[List[int], List[int]] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.__get_borders (List[List[Cell]] cells) static private
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter._merge_close_borders(), and dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.split().
__sort_unique()
np.ndarray dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.__sort_unique (List[int] borders) static private
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.split().
__split_one_cell()
None dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.__split_one_cell (Cell cell, np.ndarray horizontal_borders, np.ndarray vertical_borders, List[List[Cell]] result_matrix) static private
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.split().
_merge_close_borders()
List[List[Cell]] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter._merge_close_borders (self, List[List[Cell]] cells) protected
merge close borders into one border
Parameters
cells table in list of rows form
Returns
: cells with merged borders
References dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.__get_border_dict(), dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.__get_borders(), and dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.eps.
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.split().
split()
List[List[Cell]] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.split (self, List[List[Cell]] cells)
split merged cells
References dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.__get_borders(), dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.__sort_unique(), dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.__split_one_cell(), and dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter._merge_close_borders().
Member Data Documentation
eps
dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter.eps
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.cell_splitter.CellSplitter._merge_close_borders().
The documentation for this class was generated from the following file:
dedoc/readers/pdf_reader/pdf_image_reader/table_recognizer/cell_splitter.py