Dedoc: dedoc.common.exceptions.tabby_pdf_error.TabbyPdfError Class Reference
dedoc.common.exceptions.tabby_pdf_error.TabbyPdfError Class Reference
\par \b Purpose\/ \: To signal that the TabbyPDF external tool has failed, resulting in an HTTP 500 response.
Public Member Functions
None __init__ (self, str msg, Optional[str] msg_api=None, Optional[str] filename=None, Optional[str] version=None)
\par \b Purpose\/ \: To initialize the error with a fixed HTTP 500 code, preserving full DedocError context.
str __str__ (self)
\par \b Purpose\/ \: To provide a human-readable string representation of the error.
None __init__ (self, str msg, Optional[str] msg_api=None, Optional[str] filename=None, Optional[str] version=None, Optional[dict] metadata=None, Optional[int] code=None)
\par \b Purpose\/ \: To initialize a DedocError with full error context — message, API message, filename, version, metadata, and HTTP status code.
str __str__ (self)
\par \b Purpose\/ \: To provide a human-readable string representation of the error for logging and debugging.
Additional Inherited Members
Static Public Member Functions inherited from dedoc.common.exceptions.dedoc_error.DedocError
"DedocError" from_dict (dict error_dict)
\par \b Purpose\/ \: To reconstruct a DedocError instance from a dictionary, enabling error deserialization from JSON responses or stored error records.
Public Attributes inherited from dedoc.common.exceptions.dedoc_error.DedocError
msg
msg_api
filename
version
metadata
code
Detailed Description
\par \b Purpose\/ \: To signal that the TabbyPDF external tool has failed, resulting in an HTTP 500 response.
Constructor & Destructor Documentation
__init__()
None dedoc.common.exceptions.tabby_pdf_error.TabbyPdfError.__init__ (self, str msg, Optional[str] msg_api = None, Optional[str] filename = None, Optional[str] version = None)
\par \b Purpose\/ \: To initialize the error with a fixed HTTP 500 code, preserving full DedocError context.
\par \b Uses\/ \: DedocError.__init__ \par \b I/O\/ \: (msg: str, msg_api: Optional[str], filename: Optional[str], version: Optional[str]) -> None \par \b Complexity\/ \: 2
Reimplemented from dedoc.common.exceptions.dedoc_error.DedocError.
References dedoc.common.exceptions.tabby_pdf_error.TabbyPdfError.__init__().
Referenced by dedoc.common.exceptions.tabby_pdf_error.TabbyPdfError.__init__(), and dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
__str__()
str dedoc.common.exceptions.tabby_pdf_error.TabbyPdfError.__str__ (self)
\par \b Purpose\/ \: To provide a human-readable string representation of the error.
\par \b I/O\/ \: None -> str \par \b Complexity\/ \: 1
Reimplemented from dedoc.common.exceptions.dedoc_error.DedocError.
Referenced by dedoc.data_structures.annotation.Annotation.__repr__(), dedoc.readers.pdf_reader.data_classes.tables.cell.Cell.__repr__(), dedoc.readers.pdf_reader.data_classes.text_with_bbox.TextWithBBox.__repr__(), dedoc.readers.pdf_reader.data_classes.word_with_bbox.WordWithBBox.__repr__(), and dedoc.structure_extractors.feature_extractors.list_features.prefix.prefix.LinePrefix.__repr__().
The documentation for this class was generated from the following file:
dedoc/common/exceptions/tabby_pdf_error.py