Dedoc: dedoc.converters.concrete_converters.png_converter.PNGConverter Class Reference
dedoc.converters.concrete_converters.png_converter.PNGConverter Class Reference
\par \b Purpose\/ \: To convert image documents (.bmp, .jpg, .tiff, .hdr, etc.) into the PNG format using PIL (Pillow) for standard images and OpenCV for exotic formats.
Public Member Functions
None __init__ (self, *Optional[dict] config=None)
\par \b Purpose\/ \: To initialize the converter with image-like extension and MIME type registries from the global extensions configuration.
str convert (self, str file_path, Optional[dict] parameters=None)
\par \b Purpose\/ \: To convert an image file to PNG: uses OpenCV (cv2) for exotic formats (.hdr, .pic, .sr, .ras, .j2k) and PIL/Pillow for all other image types.
Public Member Functions inherited from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter
None __init__ (self, *Optional[dict] config=None, Optional[Set[str]] converted_extensions=None, Optional[Set[str]] converted_mimes=None)
\par \b Purpose\/ \: To initialize the converter with configuration, supported extension sets, and a configurable timeout/watchdog period for subprocess calls.
bool can_convert (self, Optional[str] file_path=None, Optional[str] extension=None, Optional[str] mime=None, Optional[dict] parameters=None)
\par \b Purpose\/ \: To determine whether this converter can handle a file by matching its extension or MIME type against the converter's supported sets.
str convert (self, str file_path, Optional[dict] parameters=None)
\par \b Purpose\/ \: To convert a file to the target format.
Additional Inherited Members
Public Attributes inherited from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter
timeout
period_checking
config
logger
Protected Member Functions inherited from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter
None _run_subprocess (self, List[str] command, str filename, str expected_path)
\par \b Purpose\/ \: To execute an external conversion command with timeout handling, error extraction from stderr, and graceful ConversionError on failure.
Protected Attributes inherited from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter
_converted_extensions
_converted_mimes
Detailed Description
\par \b Purpose\/ \: To convert image documents (.bmp, .jpg, .tiff, .hdr, etc.) into the PNG format using PIL (Pillow) for standard images and OpenCV for exotic formats.
Converts image-like (.bmp, .jpg, .tiff, etc.) documents into PNG. Look to the :class:~dedoc.converters.AbstractConverter documentation to get the information about the methods' parameters.
Constructor & Destructor Documentation
__init__()
None dedoc.converters.concrete_converters.png_converter.PNGConverter.__init__ (self, *Optional[dict] config = None)
\par \b Purpose\/ \: To initialize the converter with image-like extension and MIME type registries from the global extensions configuration.
\par \b Uses\/ \: converted_extensions, converted_mimes \par \b I/O\/ \: config: Optional[dict] -> None \par \b Complexity\/ \: 2
Reimplemented from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter.
References dedoc.converters.concrete_converters.png_converter.PNGConverter.__init__().
Referenced by dedoc.converters.concrete_converters.png_converter.PNGConverter.__init__(), and dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
convert()
str dedoc.converters.concrete_converters.png_converter.PNGConverter.convert (self, str file_path, Optional[dict] parameters = None)
\par \b Purpose\/ \: To convert an image file to PNG: uses OpenCV (cv2) for exotic formats (.hdr, .pic, .sr, .ras, .j2k) and PIL/Pillow for all other image types.
\par \b Uses\/ \: cv2, PIL.Image, UnidentifiedImageError, os, splitext_, ConversionError \par \b I/O\/ \: file_path: str, parameters: Optional[dict] -> str \par \b Complexity\/ \: 5
Convert the image-like documents into files with .png extension.
Reimplemented from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter.
The documentation for this class was generated from the following file:
dedoc/converters/concrete_converters/png_converter.py