Dedoc: dedoc.api.schema.annotation.Annotation Class Reference
dedoc.api.schema.annotation.Annotation Class Reference
\par \b Purpose\/ \: Represent a single inline annotation (e.g., bold, italic, link) spanning a character range within document text.
Static Public Attributes
int start = Field(description="Start of the annotated text", example=0)
int end = Field(description="End of the annotated text (end isn't included)", example=5)
str name = Field(description="Annotation name", example="italic")
str value = Field(description="Annotation value. For example, it may be font size value for size type", example="True")
Detailed Description
\par \b Purpose\/ \: Represent a single inline annotation (e.g., bold, italic, link) spanning a character range within document text.
\par \b I/O\/ \: (int, int, str, str) -> JSON serializable model
The piece of information about the text line: it's appearance or links to another document object. For example Annotation(1, 13, "italic", "True") says that text between 1st and 13th symbol was written in italic.
:ivar start: start of the annotated text :ivar end: end of the annotated text (end isn't included) :ivar name: annotation's name, specific for each type of annotation :ivar value: information about annotated text, depends on the type of annotation, e.g. "True"/"False", "10.0", etc.
:vartype start: int :vartype end: int :vartype name: str :vartype value: str
Member Data Documentation
end
int dedoc.api.schema.annotation.Annotation.end = Field(description="End of the annotated text (end isn't included)", example=5) static
Referenced by dedoc.data_structures.annotation.Annotation.__init__(), dedoc.utils.annotation_merger.ExtendedAnnotation.add(), and dedoc.data_structures.annotation.Annotation.to_api_schema().
name
str dedoc.api.schema.annotation.Annotation.name = Field(description="Annotation name", example="italic") static
Referenced by dedoc.structure_extractors.feature_extractors.list_features.prefix.prefix.LinePrefix.__eq__(), dedoc.data_structures.annotation.Annotation.__init__(), dedoc.data_structures.annotation.Annotation.to_api_schema(), and dedoc.readers.pdf_reader.data_classes.tables.location.Location.to_dict().
start
int dedoc.api.schema.annotation.Annotation.start = Field(description="Start of the annotated text", example=0) static
Referenced by dedoc.data_structures.annotation.Annotation.__init__(), dedoc.utils.annotation_merger.ExtendedAnnotation.add(), and dedoc.data_structures.annotation.Annotation.to_api_schema().
value
str dedoc.api.schema.annotation.Annotation.value = Field(description="Annotation value. For example, it may be font size value for size type", example="True") static
Referenced by dedoc.data_structures.annotation.Annotation.__init__(), and dedoc.data_structures.annotation.Annotation.to_api_schema().
The documentation for this class was generated from the following file:
dedoc/api/schema/annotation.py