Dedoc: dedoc.converters.concrete_converters.excel_converter.ExcelConverter Class Reference
dedoc.converters.concrete_converters.excel_converter.ExcelConverter Class Reference
\par \b Purpose\/ \: To convert xlsx-like documents (.xls, .ods) into XLSX format using the LibreOffice soffice headless application.
Public Member Functions
None __init__ (self, *Optional[dict] config=None)
\par \b Purpose\/ \: To initialize the converter with excel-like extension and MIME type registries from the global extensions configuration.
str convert (self, str file_path, Optional[dict] parameters=None)
\par \b Purpose\/ \: To convert an xlsx-like document to .xlsx by invoking soffice –headless –convert-to xlsx and waiting for the output file.
Public Member Functions inherited from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter
None __init__ (self, *Optional[dict] config=None, Optional[Set[str]] converted_extensions=None, Optional[Set[str]] converted_mimes=None)
\par \b Purpose\/ \: To initialize the converter with configuration, supported extension sets, and a configurable timeout/watchdog period for subprocess calls.
bool can_convert (self, Optional[str] file_path=None, Optional[str] extension=None, Optional[str] mime=None, Optional[dict] parameters=None)
\par \b Purpose\/ \: To determine whether this converter can handle a file by matching its extension or MIME type against the converter's supported sets.
str convert (self, str file_path, Optional[dict] parameters=None)
\par \b Purpose\/ \: To convert a file to the target format.
Additional Inherited Members
Public Attributes inherited from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter
timeout
period_checking
config
logger
Protected Member Functions inherited from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter
None _run_subprocess (self, List[str] command, str filename, str expected_path)
\par \b Purpose\/ \: To execute an external conversion command with timeout handling, error extraction from stderr, and graceful ConversionError on failure.
Protected Attributes inherited from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter
_converted_extensions
_converted_mimes
Detailed Description
\par \b Purpose\/ \: To convert xlsx-like documents (.xls, .ods) into XLSX format using the LibreOffice soffice headless application.
Converts xlsx-like documents (.xls, .ods) into XLSX using the soffice application. Look to the :class:~dedoc.converters.AbstractConverter documentation to get the information about the methods' parameters.
Constructor & Destructor Documentation
__init__()
None dedoc.converters.concrete_converters.excel_converter.ExcelConverter.__init__ (self, *Optional[dict] config = None)
\par \b Purpose\/ \: To initialize the converter with excel-like extension and MIME type registries from the global extensions configuration.
\par \b Uses\/ \: converted_extensions, converted_mimes \par \b I/O\/ \: config: Optional[dict] -> None \par \b Complexity\/ \: 2
Reimplemented from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter.
References dedoc.converters.concrete_converters.excel_converter.ExcelConverter.__init__().
Referenced by dedoc.converters.concrete_converters.excel_converter.ExcelConverter.__init__(), and dedoc.api.process_handler.CancellationProcessHandler.handle().
Member Function Documentation
convert()
str dedoc.converters.concrete_converters.excel_converter.ExcelConverter.convert (self, str file_path, Optional[dict] parameters = None)
\par \b Purpose\/ \: To convert an xlsx-like document to .xlsx by invoking soffice –headless –convert-to xlsx and waiting for the output file.
\par \b Uses\/ \: os, splitext_, _run_subprocess \par \b I/O\/ \: file_path: str, parameters: Optional[dict] -> str \par \b Complexity\/ \: 4
Convert the xlsx-like documents into files with .xlsx extension using the soffice application.
Reimplemented from dedoc.converters.concrete_converters.abstract_converter.AbstractConverter.
References dedoc.converters.concrete_converters.abstract_converter.AbstractConverter._run_subprocess().
The documentation for this class was generated from the following file:
dedoc/converters/concrete_converters/excel_converter.py