Dedoc: dedoc.utils.langchain Namespace Reference
dedoc.utils.langchain Namespace Reference
Functions
_module_contract ()
\par \b Module Contract\/ \:\par \b Purpose\/ \: To dynamically construct manager configuration dictionaries that wire together converters, readers, structure extractors, and metadata extractors based on file extension and parsing parameters.
dict make_manager_config (str file_path, str split, dict parsing_params)
\par \b Purpose\/ \: To build a complete manager configuration dictionary by selecting the appropriate converter, reader, and metadata extractor for a given file extension, enabling dynamic pipeline assembly.
dict make_manager_pdf_config (str file_path, str split, dict parsing_params)
\par \b Purpose\/ \: To build a PDF-only manager configuration, raising BadFileFormatError for non-PDF extensions to enforce input type constraints.
dict make_minimal_manager_config (str split, dict parsing_params)
\par \b Purpose\/ \: To construct a minimal manager configuration with all available converters and readers for attachment-heavy or multi-format scenarios.
Variables
logger = logging.getLogger(__name__)
dict supported_extensions
Function Documentation
_module_contract()
dedoc.utils.langchain._module_contract () protected
\par \b Module Contract\/ \:\par \b Purpose\/ \: To dynamically construct manager configuration dictionaries that wire together converters, readers, structure extractors, and metadata extractors based on file extension and parsing parameters.
Acts as the central factory for Dedoc processing pipelines. \par \b Scope\/ \: Manager config factory for full pipeline, PDF-only pipeline, and minimal attachment-handling pipeline. \par \b Input\/ \: File path, split mode, parsing parameters dict. \par \b Output\/ \: Manager configuration dict with converter, reader, structure_extractor, structure_constructor, document_metadata_extractor, attachments_handler. \par \b Links\/ \: [USES_API(7): dedoc.converters, dedoc.readers, dedoc.structure_extractors, dedoc.metadata_extractors] \par \b Invariants\/ \:
make_manager_config ALWAYS returns a config dict with all 6 required keys.
If with_attachments is True, make_minimal_manager_config is used instead of extension-based routing.
Unknown extensions raise BadFileFormatError. \par \b Rationale\/ \:
Q: Why use lazy imports inside functions? A: Avoids circular import issues and reduces startup memory by loading only the components needed for a specific file type. \par \b Changes\/ \:
LAST_CHANGE: [v1.0.0 – Added SEMANTIC TEMPLATE markup and LDD logging] \par \b Module Map\/ \:
DATA 9[Extension format groups] => supported_extensions FUNC 10[Full pipeline manager config factory] => make_manager_config FUNC 9[PDF-only pipeline manager config factory] => make_manager_pdf_config FUNC 8[Minimal attachment pipeline config] => make_minimal_manager_config \par \b Use Cases\/ \:
[make_manager_config]: DedocManager → SelectPipeline → Appropriate reader/converter/extractors wired
make_manager_config()
dict dedoc.utils.langchain.make_manager_config (str file_path, str split, dict parsing_params)
\par \b Purpose\/ \: To build a complete manager configuration dictionary by selecting the appropriate converter, reader, and metadata extractor for a given file extension, enabling dynamic pipeline assembly.
\par \b Uses\/ \: get_mime_extension, get_param_with_attachments, BadFileFormatError \par \b I/O\/ \: (str, str, dict) -> dict \par \b Complexity\/ \: 9
References dedoc.utils.langchain.make_minimal_manager_config().
make_manager_pdf_config()
dict dedoc.utils.langchain.make_manager_pdf_config (str file_path, str split, dict parsing_params)
\par \b Purpose\/ \: To build a PDF-only manager configuration, raising BadFileFormatError for non-PDF extensions to enforce input type constraints.
\par \b Uses\/ \: get_mime_extension, get_param_with_attachments, BadFileFormatError \par \b I/O\/ \: (str, str, dict) -> dict \par \b Complexity\/ \: 8
References dedoc.utils.langchain.make_minimal_manager_config().
make_minimal_manager_config()
dict dedoc.utils.langchain.make_minimal_manager_config (str split, dict parsing_params)
\par \b Purpose\/ \: To construct a minimal manager configuration with all available converters and readers for attachment-heavy or multi-format scenarios.
\par \b I/O\/ \: (str, dict) -> dict \par \b Complexity\/ \: 7
Referenced by dedoc.utils.langchain.make_manager_config(), and dedoc.utils.langchain.make_manager_pdf_config().
Variable Documentation
logger
dedoc.utils.langchain.logger = logging.getLogger(__name__)
supported_extensions
dict dedoc.utils.langchain.supported_extensions
Initial value:
=  {
    format_group: {*recognized_extensions._asdict()[format_group], *converted_extensions._asdict()[format_group]}
    for format_group in recognized_extensions._asdict().keys()
}