var namespacededoc_1_1metadata__extractors_1_1concrete__metadata__extractors_1_1base__metadata__extractor =
[
    [ "BaseMetadataExtractor", "classdedoc_1_1metadata__extractors_1_1concrete__metadata__extractors_1_1base__metadata__extractor_1_1BaseMetadataExtractor.html", "classdedoc_1_1metadata__extractors_1_1concrete__metadata__extractors_1_1base__metadata__extractor_1_1BaseMetadataExtractor" ],
    [ "_module_contract", "namespacededoc_1_1metadata__extractors_1_1concrete__metadata__extractors_1_1base__metadata__extractor.html#ad5833596012f5672f14fc1677eb824b1", null ]
];