Dedoc: dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils Namespace Reference
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils Namespace Reference
Classes
class Language
Functions
str correct_string_incorrect_chars (str input_string)
str correct_word_incorrect_chars (str input_string)
str substitute_chars_by_dict (dict substitutions_dict, Union[str, List[str]] word)
None correctly_resize (str image_path, tuple size=(28, 28))
bool is_empty (str image_path)
_module_contract ()
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
Variables
logger = logging.getLogger(__name__)
str junk_string = "_junkstring"
char_pool
other
convert
convertdictrus = convert.get("convert_chars_to_rus")
convertdicteng = dict((v, k) for k, v in convertdictrus.items())
list rus
list eng
list only_rus = ["я", "й", "ц", "б", "ж", "з", "д", "л", "ф", "ш", "щ", "ч", "ъ", "ь", "э", "ю", "г"]
list only_eng = ["q", "w", "f", "i", "j", "l", "z", "s", "v", "g"]
Function Documentation
_module_contract()
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils._module_contract () protected
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
\par \b Scope\/ \: Utility functions for document processing. \par \b Input\/ \: [File path (str), parameters (Optional[dict]) — document on disk.] \par \b Output\/ \: [UnstructuredDocument with lines, tables, attachments, and warnings.] \par \b Links\/ \: [USES_API(9): dedoc.data_structures.*; USES_API(8): dedoc.readers.BaseReader] \par \b Invariants\/ \:
read() ALWAYS returns an UnstructuredDocument. \par \b Rationale\/ \:
Q: Why is this reader separated from others? A: Each reader handles one format family — isolation prevents format coupling and simplifies extension. \par \b Changes\/ \:
LAST_CHANGE: [v1.0.0 – Added SEMANTIC TEMPLATE markup and LDD logging.] \par \b Module Map\/ \:
CLASS [2][Language reader/processor] => Language FUNC [5][correct_string_incorrect_chars utility/helper] => correct_string_incorrect_chars FUNC [5][correct_word_incorrect_chars utility/helper] => correct_word_incorrect_chars FUNC [5][substitute_chars_by_dict utility/helper] => substitute_chars_by_dict FUNC [5][correctly_resize utility/helper] => correctly_resize FUNC [5][is_empty utility/helper] => is_empty \par \b Use Cases\/ \:
[read]: System (Pipeline) → ParseDocument(PDF) → UnstructuredDocument
correct_string_incorrect_chars()
str dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.correct_string_incorrect_chars (str input_string)
References dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.correct_word_incorrect_chars().
correct_word_incorrect_chars()
str dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.correct_word_incorrect_chars (str input_string)
References dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.substitute_chars_by_dict().
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.correct_string_incorrect_chars().
correctly_resize()
None dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.correctly_resize (str image_path, tuple size = (28, 28))
is_empty()
bool dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.is_empty (str image_path)
substitute_chars_by_dict()
str dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.substitute_chars_by_dict (dict substitutions_dict, Union[str, List[str]] word)
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.correct_word_incorrect_chars().
Variable Documentation
char_pool
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.char_pool
convert
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.convert
Initial value:
=  dict(
    convert_chars_to_rus={
        "a": "а", "b": "в", "c": "с", "d": "д", "e": "е", "h": "н", "k": "к", "m": "м", "o": "о", "p": "р", "r": "г",
        "y": "у", "t": "т", "u": "и", "x": "х"
    }
)
convertdicteng
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.convertdicteng = dict((v, k) for k, v in convertdictrus.items())
convertdictrus
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.convertdictrus = convert.get("convert_chars_to_rus")
eng
list dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.eng
Initial value:
=  [
    "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v",
    "w", "x", "y", "z", "о", "а", "с"
]
junk_string
str dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.junk_string = "_junkstring"
logger
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.logger = logging.getLogger(__name__)
only_eng
list dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.only_eng = ["q", "w", "f", "i", "j", "l", "z", "s", "v", "g"]
only_rus
list dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.only_rus = ["я", "й", "ц", "б", "ж", "з", "д", "л", "ф", "ш", "щ", "ч", "ъ", "ь", "э", "ю", "г"]
other
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.other
Initial value:
=  dict(
    bottom_align=[",", ".", "_"],
    dont_aug=[
        ",", "dot", "\\", "`", "_", "-", "=", ";", ":", "quotedbl", "colon", "backslash", ")", "(", "[", "]", "<",
        ">", "~", "+", "'"
    ]
)
rus
list dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.utils.rus
Initial value:
=  [
    "а", "б", "в", "г", "д", "е", "ж", "з", "и", "й", "к", "л", "м", "н", "о", "п", "р", "с", "т", "у", "ф", "х",
    "ц", "ч", "ш", "щ", "ъ", "ы", "ь", "э", "ю", "я", "o", "a", "c", "e", "x", "k"
]