Dedoc: dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf Namespace Reference
dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf Namespace Reference
Functions
str _jar_path ()
bytes _run (str path=None, str encoding="utf-8")
dict extract (str path)
_module_contract ()
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
Variables
str TABBY_JAVA_VERSION = "2.0.0"
str JAR_NAME = "ispras_tbl_extr.jar"
JAR_DIR = os.path.abspath(os.path.dirname(__file__))
str JAVA_NOT_FOUND_ERROR = "`java` command is not found from this Python process. Please ensure Java is installed and PATH is set for `java`"
dict DEFAULT_CONFIG = {"JAR_PATH": os.path.join(JAR_DIR, JAR_NAME)}
Function Documentation
_jar_path()
str dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf._jar_path () protected
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf._run().
_module_contract()
dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf._module_contract () protected
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
\par \b Scope\/ \: Document parsing pipeline: PDF format reading. \par \b Input\/ \: [File path (str), parameters (Optional[dict]) — document on disk.] \par \b Output\/ \: [UnstructuredDocument with lines, tables, attachments, and warnings.] \par \b Links\/ \: [USES_API(9): dedoc.data_structures.*; USES_API(8): dedoc.readers.BaseReader] \par \b Invariants\/ \:
read() ALWAYS returns an UnstructuredDocument. \par \b Rationale\/ \:
Q: Why is this reader separated from others? A: Each reader handles one format family — isolation prevents format coupling and simplifies extension. \par \b Changes\/ \:
LAST_CHANGE: [v1.0.0 – Added SEMANTIC TEMPLATE markup and LDD logging.] \par \b Module Map\/ \:
FUNC [5][_jar_path utility/helper] => _jar_path FUNC [5][_run utility/helper] => _run FUNC [5][extract utility/helper] => extract \par \b Use Cases\/ \:
[read]: System (Pipeline) → ParseDocument(PDF) → UnstructuredDocument
_run()
bytes dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf._run (str path = None, str encoding = "utf-8") protected
References dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf._jar_path().
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf.extract().
extract()
dict dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf.extract (str path)
References dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf._run().
Variable Documentation
DEFAULT_CONFIG
dict dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf.DEFAULT_CONFIG = {"JAR_PATH": os.path.join(JAR_DIR, JAR_NAME)}
JAR_DIR
dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf.JAR_DIR = os.path.abspath(os.path.dirname(__file__))
JAR_NAME
str dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf.JAR_NAME = "ispras_tbl_extr.jar"
JAVA_NOT_FOUND_ERROR
str dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf.JAVA_NOT_FOUND_ERROR = "`java` command is not found from this Python process. Please ensure Java is installed and PATH is set for `java`"
TABBY_JAVA_VERSION
str dedoc.readers.pdf_reader.pdf_txtlayer_reader.tabbypdf.tabbypdf.TABBY_JAVA_VERSION = "2.0.0"