Dedoc: dedoc.utils.train_dataset_utils Namespace Reference
dedoc.utils.train_dataset_utils Namespace Reference
Functions
_module_contract ()
\par \b Module Contract\/ \:\par \b Purpose\/ \: To provide utilities for preparing training datasets from document processing results: saving LineWithMeta objects as JSON lines, merging lines with same BBox, and managing image/document paths for ML model training workflows.
Image __to_pil (np.ndarray image)
\par \b Purpose\/ \: To convert a numpy array to a PIL Image.
None __create_images_path (dict config)
\par \b Purpose\/ \: To assert labeling mode is configured and create the intermediate data directory if missing.
str get_path_original_documents (dict config)
\par \b Purpose\/ \: To resolve and create the directory path for original training documents.
str _get_images_path (dict config, str document_name)
\par \b Purpose\/ \: To resolve and create the per-document images directory for storing rendered page images.
None save_line_with_meta (List[LineWithMeta] lines, str original_document, *dict config)
\par \b Purpose\/ \: To save a list of LineWithMeta objects as JSON lines in the training dataset, merging lines with identical bounding boxes before writing.
List[LineWithMeta] __postprocess_lines (List[LineWithMeta] lines)
\par \b Purpose\/ \: To merge consecutive lines that share the same bounding box, reducing dataset fragmentation for ML training.
str get_original_document_path (str path2documents, List[dict] page)
\par \b Purpose\/ \: To resolve the full filesystem path to an original document from a page metadata entry.
Variables
logger = logging.getLogger(__name__)
Function Documentation
__create_images_path()
None dedoc.utils.train_dataset_utils.__create_images_path (dict config) private
\par \b Purpose\/ \: To assert labeling mode is configured and create the intermediate data directory if missing.
\par \b I/O\/ \: dict -> None \par \b Complexity\/ \: 3
Referenced by dedoc.utils.train_dataset_utils.save_line_with_meta().
__postprocess_lines()
List[LineWithMeta] dedoc.utils.train_dataset_utils.__postprocess_lines (List[LineWithMeta] lines) private
\par \b Purpose\/ \: To merge consecutive lines that share the same bounding box, reducing dataset fragmentation for ML training.
\par \b I/O\/ \: List[LineWithMeta] -> List[LineWithMeta] \par \b Complexity\/ \: 5
Referenced by dedoc.utils.train_dataset_utils.save_line_with_meta().
__to_pil()
Image dedoc.utils.train_dataset_utils.__to_pil (np.ndarray image) private
\par \b Purpose\/ \: To convert a numpy array to a PIL Image.
\par \b Uses\/ \: PIL.Image \par \b I/O\/ \: np.ndarray -> Image \par \b Complexity\/ \: 2
_get_images_path()
str dedoc.utils.train_dataset_utils._get_images_path (dict config, str document_name) protected
\par \b Purpose\/ \: To resolve and create the per-document images directory for storing rendered page images.
\par \b Uses\/ \: get_path_original_documents \par \b I/O\/ \: (dict, str) -> str \par \b Complexity\/ \: 3
References dedoc.utils.train_dataset_utils.get_path_original_documents().
_module_contract()
dedoc.utils.train_dataset_utils._module_contract () protected
\par \b Module Contract\/ \:\par \b Purpose\/ \: To provide utilities for preparing training datasets from document processing results: saving LineWithMeta objects as JSON lines, merging lines with same BBox, and managing image/document paths for ML model training workflows.
\par \b Scope\/ \: Training dataset creation, line postprocessing (BBox deduplication), image path management, document path resolution. \par \b Input\/ \: LineWithMeta objects, config dict, original document path. \par \b Output\/ \: JSON lines files, image directories, document paths. \par \b Links\/ \: [USES_API(6): PIL, numpy, json] \par \b Invariants\/ \:
__postprocess_lines merges consecutive lines with identical bounding boxes.
save_line_with_meta always creates intermediate directories if they do not exist. \par \b Rationale\/ \:
Q: Why merge lines with identical BBox? A: Some readers produce multiple LineWithMeta fragments for the same visual region. Pre-merging simplifies annotation and reduces dataset noise. \par \b Changes\/ \:
LAST_CHANGE: [v1.0.0 – Added SEMANTIC TEMPLATE markup and LDD logging] \par \b Module Map\/ \:
FUNC 3[numpy to PIL] => __to_pil FUNC 4[Create images path] => __create_images_path FUNC 5[Original documents path] => get_path_original_documents FUNC 4[Per-document images path] => _get_images_path FUNC 7[Save lines as JSON] => save_line_with_meta FUNC 6[Merge lines with same BBox] => __postprocess_lines FUNC 4[Get original document file path] => get_original_document_path \par \b Use Cases\/ \:
[save_line_with_meta]: DataPipeline → ExportTrainingData → Lines written to JSON lines file
get_original_document_path()
str dedoc.utils.train_dataset_utils.get_original_document_path (str path2documents, List[dict] page)
\par \b Purpose\/ \: To resolve the full filesystem path to an original document from a page metadata entry.
\par \b I/O\/ \: (str, List[dict]) -> str \par \b Complexity\/ \: 2
get_path_original_documents()
str dedoc.utils.train_dataset_utils.get_path_original_documents (dict config)
\par \b Purpose\/ \: To resolve and create the directory path for original training documents.
\par \b I/O\/ \: dict -> str \par \b Complexity\/ \: 3
Referenced by dedoc.utils.train_dataset_utils._get_images_path().
save_line_with_meta()
None dedoc.utils.train_dataset_utils.save_line_with_meta (List[LineWithMeta] lines, str original_document, *dict config)
\par \b Purpose\/ \: To save a list of LineWithMeta objects as JSON lines in the training dataset, merging lines with identical bounding boxes before writing.
\par \b Uses\/ \: __create_images_path, __postprocess_lines \par \b I/O\/ \: (List[LineWithMeta], str, *, config: dict) -> None \par \b Complexity\/ \: 5
References dedoc.utils.train_dataset_utils.__create_images_path(), and dedoc.utils.train_dataset_utils.__postprocess_lines().
Variable Documentation
logger
dedoc.utils.train_dataset_utils.logger = logging.getLogger(__name__)