var namespacededoc_1_1structure__extractors_1_1concrete__structure__extractors_1_1law__structure__excractor =
[
    [ "LawStructureExtractor", "classdedoc_1_1structure__extractors_1_1concrete__structure__extractors_1_1law__structure__excractor_1_1LawStructureExtractor.html", "classdedoc_1_1structure__extractors_1_1concrete__structure__extractors_1_1law__structure__excractor_1_1LawStructureExtractor" ],
    [ "_module_contract", "namespacededoc_1_1structure__extractors_1_1concrete__structure__extractors_1_1law__structure__excractor.html#aa5328dbcba84c4f544365c6f0c1e830c", null ],
    [ "logger", "namespacededoc_1_1structure__extractors_1_1concrete__structure__extractors_1_1law__structure__excractor.html#a2faecf0e99cadc1ce603b555bb9019eb", null ]
];