Dedoc: dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper Namespace Reference
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper Namespace Reference
Functions
List[str] generate_images (Path save_path, Path font_path, int index, List[str] uni_char_pool)
Generate images for specified unicode characters from font.
Tuple[List[str], Dict[str, str], List[str], List[int]] generate_all_images (Path save_path, Path font_path)
Generate images for all glyphs in font.
None process_glyph (str name, Dict[str, any] font, Path save_path, List[str] save_paths, Dict[str, str] font_white_spaces, List[str] names, List[int] codes, List[str] not_worth_outputting)
Process individual glyph from font.
bool should_skip_glyph (str name, Dict[str, any] font)
Check if glyph should be skipped.
int get_unicode_value (str name, Dict[str, any] font)
Get unicode value for glyph name.
str get_filename (str name, int unicode_val)
Get filename for glyph based on unicode value or name.
bool is_empty_glyph (Dict[str, any] font, str name)
Check if glyph is empty.
None handle_empty_glyph (str filename, Dict[str, str] font_white_spaces, List[str] not_worth_outputting)
Handle empty glyph case.
None export_glyph (str name, Dict[str, Dict[str, any]] font, Path save_path, str filename, List[str] save_paths, List[str] names, List[int] codes, int unicode_val)
Export glyph to image file.
_module_contract ()
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
Variables
logger = logging.getLogger(__name__)
int image_size = 80
args = sys.argv[1:]
List[str] result = generate_images(Path(args[1]), Path(args[2]), int(args[3]), args[4:])
Function Documentation
_module_contract()
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper._module_contract () protected
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
\par \b Scope\/ \: Document parsing pipeline: PDF format reading. \par \b Input\/ \: [File path (str), parameters (Optional[dict]) — document on disk.] \par \b Output\/ \: [UnstructuredDocument with lines, tables, attachments, and warnings.] \par \b Links\/ \: [USES_API(9): dedoc.data_structures.*; USES_API(8): dedoc.readers.BaseReader] \par \b Invariants\/ \:
read() ALWAYS returns an UnstructuredDocument. \par \b Rationale\/ \:
Q: Why is this reader separated from others? A: Each reader handles one format family — isolation prevents format coupling and simplifies extension. \par \b Changes\/ \:
LAST_CHANGE: [v1.0.0 – Added SEMANTIC TEMPLATE markup and LDD logging.] \par \b Module Map\/ \:
FUNC [5][generate_images utility/helper] => generate_images FUNC [5][generate_all_images utility/helper] => generate_all_images FUNC [5][process_glyph utility/helper] => process_glyph FUNC [5][should_skip_glyph utility/helper] => should_skip_glyph FUNC [5][get_unicode_value utility/helper] => get_unicode_value FUNC [5][get_filename utility/helper] => get_filename FUNC [5][is_empty_glyph utility/helper] => is_empty_glyph FUNC [5][handle_empty_glyph utility/helper] => handle_empty_glyph FUNC [5][export_glyph utility/helper] => export_glyph \par \b Use Cases\/ \:
[read]: System (Pipeline) → ParseDocument(PDF) → UnstructuredDocument
export_glyph()
None dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.export_glyph (str name, Dict[str, Dict[str, any]] font, Path save_path, str filename, List[str] save_paths, List[str] names, List[int] codes, int unicode_val)
Export glyph to image file.
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.process_glyph().
generate_all_images()
Tuple[List[str], Dict[str, str], List[str], List[int]] dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.generate_all_images (Path save_path, Path font_path)
Generate images for all glyphs in font.
References dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.process_glyph().
generate_images()
List[str] dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.generate_images (Path save_path, Path font_path, int index, List[str] uni_char_pool)
Generate images for specified unicode characters from font.
get_filename()
str dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.get_filename (str name, int unicode_val)
Get filename for glyph based on unicode value or name.
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.process_glyph().
get_unicode_value()
int dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.get_unicode_value (str name, Dict[str, any] font)
Get unicode value for glyph name.
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.process_glyph().
handle_empty_glyph()
None dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.handle_empty_glyph (str filename, Dict[str, str] font_white_spaces, List[str] not_worth_outputting)
Handle empty glyph case.
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.process_glyph().
is_empty_glyph()
bool dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.is_empty_glyph (Dict[str, any] font, str name)
Check if glyph is empty.
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.process_glyph().
process_glyph()
None dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.process_glyph (str name, Dict[str, any] font, Path save_path, List[str] save_paths, Dict[str, str] font_white_spaces, List[str] names, List[int] codes, List[str] not_worth_outputting)
Process individual glyph from font.
References dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.export_glyph(), dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.get_filename(), dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.get_unicode_value(), dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.handle_empty_glyph(), dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.is_empty_glyph(), and dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.should_skip_glyph().
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.generate_all_images().
should_skip_glyph()
bool dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.should_skip_glyph (str name, Dict[str, any] font)
Check if glyph should be skipped.
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.process_glyph().
Variable Documentation
args
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.args = sys.argv[1:]
image_size
int dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.image_size = 80
logger
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.logger = logging.getLogger(__name__)
result
Tuple[List[str], Dict[str, str], List[str], List[int]] dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdf_broken_encoding.fontforge_wrapper.result = generate_images(Path(args[1]), Path(args[2]), int(args[3]), args[4:])