var namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier =
[
    [ "abstract_txtlayer_classifier", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier_1_1abstract__txtlayer__classifier.html", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier_1_1abstract__txtlayer__classifier" ],
    [ "letter_txtlayer_classifier", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier_1_1letter__txtlayer__classifier.html", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier_1_1letter__txtlayer__classifier" ],
    [ "ml_txtlayer_classifier", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier_1_1ml__txtlayer__classifier.html", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier_1_1ml__txtlayer__classifier" ],
    [ "simple_txtlayer_classifier", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier_1_1simple__txtlayer__classifier.html", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier_1_1simple__txtlayer__classifier" ],
    [ "txtlayer_feature_extractor", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier_1_1txtlayer__feature__extractor.html", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier_1_1txtlayer__feature__extractor" ],
    [ "_module_contract", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier.html#a942d482192b1442d6b0bb778053051ae", null ],
    [ "get_classifiers", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier.html#ac9b6aaeb76f8044ece19451c22dcfbb1", null ],
    [ "logger", "namespacededoc_1_1readers_1_1pdf__reader_1_1pdf__auto__reader_1_1txtlayer__classifier.html#a9eaacd88c8c10ae44a3ad4f016438222", null ]
];