var namespacededoc_1_1structure__extractors_1_1feature__extractors_1_1diploma__feature__extractor =
[
    [ "DiplomaFeatureExtractor", "classdedoc_1_1structure__extractors_1_1feature__extractors_1_1diploma__feature__extractor_1_1DiplomaFeatureExtractor.html", "classdedoc_1_1structure__extractors_1_1feature__extractors_1_1diploma__feature__extractor_1_1DiplomaFeatureExtractor" ],
    [ "_module_contract", "namespacededoc_1_1structure__extractors_1_1feature__extractors_1_1diploma__feature__extractor.html#a7f3e8b018a89f85c31b703a907bbe8c1", null ],
    [ "logger", "namespacededoc_1_1structure__extractors_1_1feature__extractors_1_1diploma__feature__extractor.html#a7f9b772b86cf4d75ceaed9620c33dd8f", null ]
];