Dedoc: dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils Namespace Reference
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils Namespace Reference
Functions
None draw_layout_element (np.ndarray image_src, List lobjs, IO file, float k_w, float k_h, PDFPage page, Tuple[int, int, int] color, Optional[str] text=None)
None draw_annotation (np.ndarray image, List[BBoxAnnotation] annotations)
BBox convert_coordinates_pdf_to_image (LTContainer lobj, float k_w, float k_h, int height_page)
BBox create_bbox (int height, float k_h, float k_w, LTContainer lobj)
str cid_to_ascii_text (Match m)
_module_contract ()
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
Variables
logger = logging.getLogger(__name__)
Function Documentation
_module_contract()
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils._module_contract () protected
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
\par \b Scope\/ \: Utility functions for document processing. \par \b Input\/ \: [File path (str), parameters (Optional[dict]) — document on disk.] \par \b Output\/ \: [UnstructuredDocument with lines, tables, attachments, and warnings.] \par \b Links\/ \: [USES_API(9): dedoc.data_structures.*; USES_API(8): dedoc.readers.BaseReader] \par \b Invariants\/ \:
read() ALWAYS returns an UnstructuredDocument. \par \b Rationale\/ \:
Q: Why is this reader separated from others? A: Each reader handles one format family — isolation prevents format coupling and simplifies extension. \par \b Changes\/ \:
LAST_CHANGE: [v1.0.0 – Added SEMANTIC TEMPLATE markup and LDD logging.] \par \b Module Map\/ \:
FUNC [5][draw_layout_element utility/helper] => draw_layout_element FUNC [5][draw_annotation utility/helper] => draw_annotation FUNC [5][convert_coordinates_pdf_to_image utility/helper] => convert_coordinates_pdf_to_image FUNC [5][create_bbox utility/helper] => create_bbox FUNC [5][cid_to_ascii_text utility/helper] => cid_to_ascii_text \par \b Use Cases\/ \:
[read]: System (Pipeline) → ParseDocument(PDF) → UnstructuredDocument
cid_to_ascii_text()
str dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils.cid_to_ascii_text (Match m)
convert_coordinates_pdf_to_image()
BBox dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils.convert_coordinates_pdf_to_image (LTContainer lobj, float k_w, float k_h, int height_page)
Referenced by dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils.create_bbox(), and dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils.draw_layout_element().
create_bbox()
BBox dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils.create_bbox (int height, float k_h, float k_w, LTContainer lobj)
References dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils.convert_coordinates_pdf_to_image().
draw_annotation()
None dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils.draw_annotation (np.ndarray image, List[BBoxAnnotation] annotations)
draw_layout_element()
None dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils.draw_layout_element (np.ndarray image_src, List lobjs, IO file, float k_w, float k_h, PDFPage page, Tuple[int, int, int] color, Optional[str] text = None)
References dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils.convert_coordinates_pdf_to_image().
Variable Documentation
logger
dedoc.readers.pdf_reader.pdf_txtlayer_reader.pdfminer_reader.pdfminer_utils.logger = logging.getLogger(__name__)