Dedoc: dedoc.readers.docx_reader.properties_extractor Namespace Reference
dedoc.readers.docx_reader.properties_extractor Namespace Reference
Functions
float spacing_to_float (Union[str, int, float] spacing)
bool check_if_true (str value)
None change_paragraph_properties (BaseProperties old_properties, Tag tree)
Changes old properties indent, size, jc, spacing_before, spacing_after if they were found in tree.
None change_run_properties (BaseProperties old_properties, Tag tree)
Changes old properties: bold, italic, underlined, size if they were found in tree.
None change_indent (BaseProperties old_properties, Tag tree)
Changes old properties: indentation if it was found in tree.
None change_size (BaseProperties old_properties, Tag tree)
Changes old properties: size if it was found in tree.
None change_jc (BaseProperties old_properties, Tag tree)
Changes old_properties: jc (alignment) if tag jc was found in tree.
None change_caps (BaseProperties old_properties, Tag tree)
Changes old_properties: caps if tag caps was found in tree.
None change_spacing (BaseProperties old_properties, Tag tree)
Changes old_properties: spacing_before, spacing_after if tag spacing was found in tree.
_module_contract ()
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse DOCX documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
Variables
logger = logging.getLogger(__name__)
Function Documentation
_module_contract()
dedoc.readers.docx_reader.properties_extractor._module_contract () protected
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse DOCX documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
\par \b Scope\/ \: Feature and metadata extraction from documents. \par \b Input\/ \: [File path (str), parameters (Optional[dict]) — document on disk.] \par \b Output\/ \: [UnstructuredDocument with lines, tables, attachments, and warnings.] \par \b Links\/ \: [USES_API(9): dedoc.data_structures.*; USES_API(8): dedoc.readers.BaseReader] \par \b Invariants\/ \:
read() ALWAYS returns an UnstructuredDocument. \par \b Rationale\/ \:
Q: Why is this reader separated from others? A: Each reader handles one format family — isolation prevents format coupling and simplifies extension. \par \b Changes\/ \:
LAST_CHANGE: [v1.0.0 – Added SEMANTIC TEMPLATE markup and LDD logging.] \par \b Module Map\/ \:
FUNC [5][spacing_to_float utility/helper] => spacing_to_float FUNC [5][check_if_true utility/helper] => check_if_true FUNC [5][change_paragraph_properties utility/helper] => change_paragraph_properties FUNC [5][change_run_properties utility/helper] => change_run_properties FUNC [5][change_indent utility/helper] => change_indent FUNC [5][change_size utility/helper] => change_size FUNC [5][change_jc utility/helper] => change_jc FUNC [5][change_caps utility/helper] => change_caps FUNC [5][change_spacing utility/helper] => change_spacing \par \b Use Cases\/ \:
[read]: System (Pipeline) → ParseDocument(DOCX) → UnstructuredDocument
change_caps()
None dedoc.readers.docx_reader.properties_extractor.change_caps (BaseProperties old_properties, Tag tree)
Changes old_properties: caps if tag caps was found in tree.
:param old_properties: Paragraph or Run :param tree: BeautifulSoup tree with properties
References dedoc.readers.docx_reader.properties_extractor.check_if_true().
change_indent()
None dedoc.readers.docx_reader.properties_extractor.change_indent (BaseProperties old_properties, Tag tree)
Changes old properties: indentation if it was found in tree.
Indentation is changed according to the following attributes in paragraph properties:
firstLine describes additional indentation to current indentation, if hanging is present firstLine is ignored
firstLineChars differs from firstLine only in measurement (one hundredths of a character unit)
hanging removes indentation from current indentation (analogous hangingChars)
start (startChars) describes classical indentation
left isn't specified in the documentation, F Main measurement 1/1440 of an inch: 1 inch is 12 char units, 1/100 char unit = 1/1200 inch = 1.2 * (1/1440 of an inch)
:param old_properties: Paragraph :param tree: BeautifulSoup tree with properties
References dedoc.readers.docx_reader.properties_extractor.spacing_to_float().
Referenced by dedoc.readers.docx_reader.properties_extractor.change_paragraph_properties().
change_jc()
None dedoc.readers.docx_reader.properties_extractor.change_jc (BaseProperties old_properties, Tag tree)
Changes old_properties: jc (alignment) if tag jc was found in tree.
Alignment values: left, right, center, both, left is default. :param old_properties: Paragraph :param tree: BeautifulSoup tree with properties
References dedoc.readers.docx_reader.properties_extractor.check_if_true().
Referenced by dedoc.readers.docx_reader.properties_extractor.change_paragraph_properties().
change_paragraph_properties()
None dedoc.readers.docx_reader.properties_extractor.change_paragraph_properties (BaseProperties old_properties, Tag tree)
Changes old properties indent, size, jc, spacing_before, spacing_after if they were found in tree.
:param old_properties: Paragraph :param tree: BeautifulSoup tree with properties
References dedoc.readers.docx_reader.properties_extractor.change_indent(), dedoc.readers.docx_reader.properties_extractor.change_jc(), dedoc.readers.docx_reader.properties_extractor.change_size(), and dedoc.readers.docx_reader.properties_extractor.change_spacing().
change_run_properties()
None dedoc.readers.docx_reader.properties_extractor.change_run_properties (BaseProperties old_properties, Tag tree)
Changes old properties: bold, italic, underlined, size if they were found in tree.
:param old_properties: Run :param tree: BeautifulSoup tree with properties
References dedoc.readers.docx_reader.properties_extractor.change_size(), and dedoc.readers.docx_reader.properties_extractor.check_if_true().
change_size()
None dedoc.readers.docx_reader.properties_extractor.change_size (BaseProperties old_properties, Tag tree)
Changes old properties: size if it was found in tree.
:param old_properties: Paragraph or Run :param tree: BeautifulSoup tree with properties
References dedoc.readers.docx_reader.properties_extractor.spacing_to_float().
Referenced by dedoc.readers.docx_reader.properties_extractor.change_paragraph_properties(), and dedoc.readers.docx_reader.properties_extractor.change_run_properties().
change_spacing()
None dedoc.readers.docx_reader.properties_extractor.change_spacing (BaseProperties old_properties, Tag tree)
Changes old_properties: spacing_before, spacing_after if tag spacing was found in tree.
Spacing is changed according to the following attributes of tag <spacing>:
after / before (measured in twentieths of a point), ignored if afterLines or afterAutospacing are specified
afterAutospacing / beforeAutospacing (we set 0 if specified) if is specified, other attributes are ignored
afterLines / beforeLines (measured in one hundredths of a line) If we have spacing "after" for the previous paragraph and spacing "before" for the next paragraph, we choose maximum between these two values.
:param old_properties: Paragraph :param tree: BeautifulSoup tree with properties
References dedoc.readers.docx_reader.properties_extractor.check_if_true(), and dedoc.readers.docx_reader.properties_extractor.spacing_to_float().
Referenced by dedoc.readers.docx_reader.properties_extractor.change_paragraph_properties().
check_if_true()
bool dedoc.readers.docx_reader.properties_extractor.check_if_true (str value)
Referenced by dedoc.readers.docx_reader.properties_extractor.change_caps(), dedoc.readers.docx_reader.properties_extractor.change_jc(), dedoc.readers.docx_reader.properties_extractor.change_run_properties(), and dedoc.readers.docx_reader.properties_extractor.change_spacing().
spacing_to_float()
float dedoc.readers.docx_reader.properties_extractor.spacing_to_float (Union[str, int, float] spacing)
Referenced by dedoc.readers.docx_reader.properties_extractor.change_indent(), dedoc.readers.docx_reader.properties_extractor.change_size(), and dedoc.readers.docx_reader.properties_extractor.change_spacing().
Variable Documentation
logger
dedoc.readers.docx_reader.properties_extractor.logger = logging.getLogger(__name__)