Dedoc: dedoc.api.api_utils Namespace Reference
dedoc.api.api_utils Namespace Reference
Functions
_module_contract ()
\par \b Module Contract\/ \:\par \b Purpose\/ \: Convert parsed document structures (TreeNode, Table, ParsedDocument) from JSON/tree representation into display formats: HTML (tree, collapsed tree), plain text, and annotated HTML with tables/attachments.
Iterator[str] __prettify_text (str text)
\par \b Purpose\/ \: Wrap text into lines of approximately 60 characters for display, yielding chunks without breaking words.
str _node2tree (TreeNode paragraph, int depth, Set[int] depths=None)
\par \b Purpose\/ \: Recursively render a TreeNode as nested HTML <details> elements for an interactive collapsible tree view.
str json2collapsed_tree (TreeNode paragraph)
\par \b Purpose\/ \: Wrap the collapsible tree HTML from _node2tree in a full HTML document with charset and styling.
str json2tree (TreeNode paragraph)
\par \b Purpose\/ \: Render a TreeNode as a flat indented HTML tree using stack-based traversal, node sorting by ID, and vertical line markers for hierarchy depth.
str __add_vertical_line (Set[int] depths, List[str] space)
\par \b Purpose\/ \: Insert vertical line pipe characters at depth positions in the indentation space list for tree visualization.
str json2html (str text, TreeNode paragraph, Optional[List[Table]] tables, Optional[List[ParsedDocument]] attachments, int tabs=0, Dict[str, int] table2id=None, Dict[str, int] attach2id=None, Optional[List[int]] prev_page_id=None)
\par \b Purpose\/ \: Main conversion function: recursively renders TreeNode with tables and attachments into a full annotated HTML document with page breaks, inline annotations, and external links.
str __value2tag (str name, str value)
\par \b Purpose\/ \: Map annotation name and value to the corresponding HTML tag (e.g., BoldAnnotation → "b", heading → "h1"-"h6").
str __annotations2html (TreeNode paragraph, Dict[str, int] table2id, Dict[str, int] attach2id, int tabs=0)
\par \b Purpose\/ \: Inject HTML tags into paragraph text at annotation character positions (start/end), handling bool annotations, links, and table/attachment references.
str table2html (Table table, Dict[str, int] table2id)
\par \b Purpose\/ \: Render a Table schema object as an HTML <table> element with border styling, merged cells (colspan/rowspan), and inline annotations.
str json2txt (TreeNode paragraph)
\par \b Purpose\/ \: Recursively extract plain text content from a TreeNode, joining paragraph text with subparagraph text via newlines.
Variables
logger = logging.getLogger(__name__)
Function Documentation
__add_vertical_line()
str dedoc.api.api_utils.__add_vertical_line (Set[int] depths, List[str] space) private
\par \b Purpose\/ \: Insert vertical line pipe characters at depth positions in the indentation space list for tree visualization.
\par \b I/O\/ \: (Set[int], List[str]) -> str \par \b Complexity\/ \: 3
Referenced by dedoc.api.api_utils.json2tree().
__annotations2html()
str dedoc.api.api_utils.__annotations2html (TreeNode paragraph, Dict[str, int] table2id, Dict[str, int] attach2id, int tabs = 0) private
\par \b Purpose\/ \: Inject HTML tags into paragraph text at annotation character positions (start/end), handling bool annotations, links, and table/attachment references.
\par \b Uses\/ \: __value2tag \par \b I/O\/ \: (TreeNode, Dict[str,int], Dict[str,int], int) -> str \par \b Complexity\/ \: 9
References dedoc.api.api_utils.__value2tag().
Referenced by dedoc.api.api_utils.json2html().
__prettify_text()
Iterator[str] dedoc.api.api_utils.__prettify_text (str text) private
\par \b Purpose\/ \: Wrap text into lines of approximately 60 characters for display, yielding chunks without breaking words.
\par \b I/O\/ \: str -> Iterator[str] \par \b Complexity\/ \: 4
Referenced by dedoc.api.api_utils._node2tree(), and dedoc.api.api_utils.json2tree().
__value2tag()
str dedoc.api.api_utils.__value2tag (str name, str value) private
\par \b Purpose\/ \: Map annotation name and value to the corresponding HTML tag (e.g., BoldAnnotation → "b", heading → "h1"-"h6").
\par \b I/O\/ \: (str, str) -> str \par \b Complexity\/ \: 4
Referenced by dedoc.api.api_utils.__annotations2html().
_module_contract()
dedoc.api.api_utils._module_contract () protected
\par \b Module Contract\/ \:\par \b Purpose\/ \: Convert parsed document structures (TreeNode, Table, ParsedDocument) from JSON/tree representation into display formats: HTML (tree, collapsed tree), plain text, and annotated HTML with tables/attachments.
\par \b Scope\/ \: Output format rendering — JSON → HTML/plain_text/tree conversion. \par \b Input\/ \: TreeNode, List[Table], List[ParsedDocument], annotation data. \par \b Output\/ \: HTML strings (tree, collapsed tree, annotated HTML), plain text. \par \b Links\/ \: [USES_API(8): dedoc.api.schema (TreeNode, Table, LineMetadata, ParsedDocument); READS_DATA_FROM(7): dedoc.data_structures.concrete_annotations, dedoc.extensions] \par \b Invariants\/ \:
json2html always returns valid HTML fragment.
All rendering functions are pure (no side effects on input data). \par \b Rationale\/ \:
Q: Why manual HTML generation instead of a template engine? A: The tree-to-HTML logic is algorithmic (depth-based indentation, annotation tag injection) — direct string construction is more efficient and self-contained than template rendering. \par \b Changes\/ \:
LAST_CHANGE: [v1.0.0 – Initial creation with semantic markup] \par \b Module Map\/ \:
FUNC 7[Prettifies text with line wrapping at 60 chars] => __prettify_text FUNC 8[Recursively renders TreeNode as collapsible HTML details] => _node2tree FUNC 8[Wraps _node2tree result in full HTML document] => json2collapsed_tree FUNC 9[Renders TreeNode as flat HTML tree with vertical lines] => json2tree FUNC 4[Adds vertical line symbols for tree depth] => __add_vertical_line FUNC 10[Main conversion: TreeNode + Tables + Attachments → annotated HTML] => json2html FUNC 6[Maps annotation name+value to HTML tag] => __value2tag FUNC 9[Injects annotation HTML tags into text at character positions] => __annotations2html FUNC 7[Renders Table as HTML table element] => table2html FUNC 5[Recursively extracts plain text from TreeNode] => json2txt \par \b Use Cases\/ \:
[json2html]: ApiEndpoint => ConvertParsedResult => ReturnHTMLResponse
[json2txt]: ApiEndpoint => ConvertParsedResult => ReturnPlainTextResponse
_node2tree()
str dedoc.api.api_utils._node2tree (TreeNode paragraph, int depth, Set[int] depths = None) protected
\par \b Purpose\/ \: Recursively render a TreeNode as nested HTML <details> elements for an interactive collapsible tree view.
\par \b Uses\/ \: __prettify_text \par \b I/O\/ \: (TreeNode, int, Set[int]) -> str \par \b Complexity\/ \: 7
References dedoc.api.api_utils.__prettify_text(), and dedoc.api.api_utils._node2tree().
Referenced by dedoc.api.api_utils._node2tree(), and dedoc.api.api_utils.json2collapsed_tree().
json2collapsed_tree()
str dedoc.api.api_utils.json2collapsed_tree (TreeNode paragraph)
\par \b Purpose\/ \: Wrap the collapsible tree HTML from _node2tree in a full HTML document with charset and styling.
\par \b Uses\/ \: _node2tree \par \b I/O\/ \: TreeNode -> str \par \b Complexity\/ \: 4
References dedoc.api.api_utils._node2tree().
json2html()
str dedoc.api.api_utils.json2html (str text, TreeNode paragraph, Optional[List[Table]] tables, Optional[List[ParsedDocument]] attachments, int tabs = 0, Dict[str, int] table2id = None, Dict[str, int] attach2id = None, Optional[List[int]] prev_page_id = None)
\par \b Purpose\/ \: Main conversion function: recursively renders TreeNode with tables and attachments into a full annotated HTML document with page breaks, inline annotations, and external links.
\par \b Uses\/ \: __annotations2html, table2html, json2html (recursive) \par \b I/O\/ \: (str, TreeNode, Optional[List[Table]], Optional[List[ParsedDocument]], int, Dict, Dict, Optional[List[int]]) -> str \par \b Complexity\/ \: 10
References dedoc.api.api_utils.__annotations2html(), and dedoc.api.api_utils.table2html().
json2tree()
str dedoc.api.api_utils.json2tree (TreeNode paragraph)
\par \b Purpose\/ \: Render a TreeNode as a flat indented HTML tree using stack-based traversal, node sorting by ID, and vertical line markers for hierarchy depth.
\par \b Uses\/ \: __prettify_text, __add_vertical_line \par \b I/O\/ \: TreeNode -> str \par \b Complexity\/ \: 8
References dedoc.api.api_utils.__add_vertical_line(), and dedoc.api.api_utils.__prettify_text().
json2txt()
str dedoc.api.api_utils.json2txt (TreeNode paragraph)
\par \b Purpose\/ \: Recursively extract plain text content from a TreeNode, joining paragraph text with subparagraph text via newlines.
\par \b I/O\/ \: TreeNode -> str \par \b Complexity\/ \: 3
table2html()
str dedoc.api.api_utils.table2html (Table table, Dict[str, int] table2id)
\par \b Purpose\/ \: Render a Table schema object as an HTML <table> element with border styling, merged cells (colspan/rowspan), and inline annotations.
\par \b Uses\/ \: __annotations2html \par \b I/O\/ \: (Table, Dict[str,int]) -> str \par \b Complexity\/ \: 7
Referenced by dedoc.api.api_utils.json2html().
Variable Documentation
logger
dedoc.api.api_utils.logger = logging.getLogger(__name__)