Dedoc: dedoc.utils.utils Namespace Reference
dedoc.utils.utils Namespace Reference
Functions
_module_contract ()
\par \b Module Contract\/ \:\par \b Purpose\/ \: To provide general-purpose utility functions for file handling, MIME type detection, encoding detection, text similarity, and datetime conversion across the Dedoc document processing pipeline.
Optional[T] list_get (List[T] ls, int index, Optional[T] default=None)
\par \b Purpose\/ \: To safely access list elements by index, returning a default value when the index is out of bounds.
Iterable[T] flatten (List[List[T]] data)
\par \b Purpose\/ \: To flatten a nested list-of-lists structure into a single iterable sequence, enabling sequential processing of grouped data.
T identity (T x)
\par \b Purpose\/ \: To return its input unchanged, serving as a no-op transform in functional pipelines.
Iterator[List[T]] get_batch (int size, Iterator[T] iterable)
\par \b Purpose\/ \: To partition an iterator into fixed-size batches, enabling chunked processing of large data streams.
Tuple[str, str] splitext_ (str path)
\par \b Purpose\/ \: To split a filename into (name, extension) correctly handling multi-dot extensions like .tar.gz that are common in compressed document formats.
Tuple[str, str] get_mime_extension (Optional[str] file_path=None, Optional[str] mime=None, Optional[str] extension=None)
\par \b Purpose\/ \: To resolve the MIME type and file extension from a file path or explicit parameters, providing a single entry point for file type identification throughout the pipeline.
str _text_from_item (dict item)
\par \b Purpose\/ \: To recursively extract text from a document item dict, descending into subparagraphs to build a complete text representation.
str document2txt (dict doc)
\par \b Purpose\/ \: To convert a structured document dictionary into a flat text string, combining header and item texts for downstream NLP processing.
str get_unique_name (str filename)
\par \b Purpose\/ \: To generate a collision-resistant unique filename using a timestamp and random suffix, ensuring safe concurrent file writes.
str save_upload_file (UploadFile upload_file, str output_dir)
\par \b Purpose\/ \: To persist an uploaded file from a FastAPI endpoint to disk with filename length validation, ensuring safe storage before processing.
str save_data_to_unique_file (str directory, str filename, bytes binary_data)
\par \b Purpose\/ \: To write binary data to a uniquely-named file in a target directory, avoiding collisions from concurrent writes.
str get_file_mime_type (str path)
\par \b Purpose\/ \: To detect the MIME type of a file from its path/extension using the mimetypes standard library.
str get_file_mime_by_content (str path)
\par \b Purpose\/ \: To determine the MIME type by inspecting file content bytes (magic number detection), falling back to puremagic when libmagic returns octet-stream.
List[str] get_extensions_by_mime (str mime)
\par \b Purpose\/ \: To retrieve all known file extensions for a given MIME type.
List[str] get_extensions_by_mimes (Set[str] mimes)
\par \b Purpose\/ \: To aggregate all file extensions for a set of MIME types, useful for filtering input by multiple accepted formats.
bool special_match (str strg, str regular_pattern=r"[^.?!,:;'\"\n\r ]")
\par \b Purpose\/ \: To check if a string consists only of a specific character class (default: non-punctuation), used for content validation.
str calculate_file_hash (str path)
\par \b Purpose\/ \: To compute an MD5 hash of a file for content-based deduplication and integrity verification.
DocumentContent get_empty_content ()
\par \b Purpose\/ \: To create an empty DocumentContent instance with a minimal valid structure, serving as a safe default for error-handling and initialization.
Optional[str] get_encoding (str path, str default=None)
\par \b Purpose\/ \: To detect the character encoding of a file (including gzip-compressed), enabling correct text extraction from diverse document sources.
float similarity (str s1, str s2)
\par \b Purpose\/ \: To compute a case-insensitive string similarity ratio using difflib.SequenceMatcher, enabling fuzzy text matching.
float similarity_levenshtein (str str1, str str2)
\par \b Purpose\/ \: To compute a case-insensitive Levenshtein ratio for high-quality fuzzy string comparison.
int convert_datetime (str time_string)
\par \b Purpose\/ \: To parse ISO/IEC 8824 datetime strings (common in PDF metadata) into Unix timestamps, handling multiple format variants including UTC offsets.
str check_filename_length (str filename)
\par \b Purpose\/ \: To truncate filenames exceeding the POSIX 255-character limit, preserving the extension to maintain file type integrity.
Dict[str, Any] send_file (str host, str file_name, str file_path, dict parameters)
\par \b Purpose\/ \: To send a file via HTTP POST multipart upload to a remote dedoc endpoint, enabling distributed document processing.
Variables
logger = logging.getLogger(__name__)
T = TypeVar("T")
tuple double_dot_extensions = (".txt.gz", ".tar.gz", ".mht.gz", ".mhtml.gz", ".note.pickle")
Function Documentation
_module_contract()
dedoc.utils.utils._module_contract () protected
\par \b Module Contract\/ \:\par \b Purpose\/ \: To provide general-purpose utility functions for file handling, MIME type detection, encoding detection, text similarity, and datetime conversion across the Dedoc document processing pipeline.
\par \b Scope\/ \: File I/O, MIME type inference, encoding detection, string similarity, datetime parsing, file hashing, batch iteration. \par \b Input\/ \: File paths, binary data, text strings, UploadFile objects. \par \b Output\/ \: File paths, MIME types, encodings, hashes, similarity scores, Unix timestamps. \par \b Links\/ \: [USES_API(7): mimetypes, hashlib, charset_normalizer, Levenshtein, requests] \par \b Invariants\/ \:
get_file_mime_type ALWAYS returns a non-empty string.
calculate_file_hash ALWAYS returns a hex digest string.
splitext_ correctly handles multi-dot extensions (e.g., .tar.gz). \par \b Rationale\/ \:
Q: Why use charset_normalizer instead of chardet? A: charset_normalizer provides more accurate encoding detection and is actively maintained. \par \b Changes\/ \:
LAST_CHANGE: [v1.0.0 – Added SEMANTIC TEMPLATE markup and LDD logging] \par \b Module Map\/ \:
FUNC 3[List access with default] => list_get FUNC 2[Flatten nested lists] => flatten FUNC 1[Identity function] => identity FUNC 4[Batch iterator] => get_batch FUNC 6[Extension splitting with multi-dot support] => splitext_ FUNC 7[MIME and extension resolver] => get_mime_extension FUNC 5[Document dict to text] => document2txt FUNC 6[Unique filename generator] => get_unique_name FUNC 7[Upload file saver] => save_upload_file FUNC 6[Binary data to unique file] => save_data_to_unique_file FUNC 7[MIME type from path] => get_file_mime_type FUNC 8[MIME type from file content] => get_file_mime_by_content FUNC 4[Extensions by MIME] => get_extensions_by_mime FUNC 4[Extensions by multiple MIMEs] => get_extensions_by_mimes FUNC 3[Regex character class match] => special_match FUNC 7[MD5 file hash] => calculate_file_hash FUNC 5[Empty DocumentContent factory] => get_empty_content FUNC 8[File encoding detection] => get_encoding FUNC 6[String similarity ratio] => similarity FUNC 6[Levenshtein similarity ratio] => similarity_levenshtein FUNC 8[ISO/IEC 8824 to Unix timestamp] => convert_datetime FUNC 5[Filename length trimmer] => check_filename_length FUNC 7[HTTP file upload sender] => send_file \par \b Use Cases\/ \:
[get_mime_extension]: Reader → ResolveFileType → MIME and extension determined
[save_upload_file]: API → ReceiveFileUpload → File saved to disk
[get_encoding]: Reader → DetectFileEncoding → Encoding identified for text extraction
_text_from_item()
str dedoc.utils.utils._text_from_item (dict item) protected
\par \b Purpose\/ \: To recursively extract text from a document item dict, descending into subparagraphs to build a complete text representation.
\par \b I/O\/ \: dict -> str \par \b Complexity\/ \: 4
References dedoc.utils.utils._text_from_item().
Referenced by dedoc.utils.utils._text_from_item(), and dedoc.utils.utils.document2txt().
calculate_file_hash()
str dedoc.utils.utils.calculate_file_hash (str path)
\par \b Purpose\/ \: To compute an MD5 hash of a file for content-based deduplication and integrity verification.
\par \b Uses\/ \: hashlib \par \b I/O\/ \: str -> str \par \b Complexity\/ \: 4
check_filename_length()
str dedoc.utils.utils.check_filename_length (str filename)
\par \b Purpose\/ \: To truncate filenames exceeding the POSIX 255-character limit, preserving the extension to maintain file type integrity.
\par \b Uses\/ \: splitext_ \par \b I/O\/ \: str -> str \par \b Complexity\/ \: 3
References dedoc.utils.utils.splitext_().
Referenced by dedoc.utils.utils.save_upload_file().
convert_datetime()
int dedoc.utils.utils.convert_datetime (str time_string)
\par \b Purpose\/ \: To parse ISO/IEC 8824 datetime strings (common in PDF metadata) into Unix timestamps, handling multiple format variants including UTC offsets.
\par \b Uses\/ \: datetime, dateutil, re \par \b I/O\/ \: str -> int \par \b Complexity\/ \: 7
document2txt()
str dedoc.utils.utils.document2txt (dict doc)
\par \b Purpose\/ \: To convert a structured document dictionary into a flat text string, combining header and item texts for downstream NLP processing.
\par \b Uses\/ \: _text_from_item \par \b I/O\/ \: dict -> str \par \b Complexity\/ \: 4
References dedoc.utils.utils._text_from_item().
flatten()
Iterable[T] dedoc.utils.utils.flatten (List[List[T]] data)
\par \b Purpose\/ \: To flatten a nested list-of-lists structure into a single iterable sequence, enabling sequential processing of grouped data.
\par \b Uses\/ \: typing \par \b I/O\/ \: List[List[T]] -> Iterable[T] \par \b Complexity\/ \: 2
get_batch()
Iterator[List[T]] dedoc.utils.utils.get_batch (int size, Iterator[T] iterable)
\par \b Purpose\/ \: To partition an iterator into fixed-size batches, enabling chunked processing of large data streams.
\par \b Uses\/ \: typing \par \b I/O\/ \: (int, Iterator[T]) -> Iterator[List[T]] \par \b Complexity\/ \: 3
get_empty_content()
DocumentContent dedoc.utils.utils.get_empty_content ()
\par \b Purpose\/ \: To create an empty DocumentContent instance with a minimal valid structure, serving as a safe default for error-handling and initialization.
\par \b Uses\/ \: DocumentContent, TreeNode, LineMetadata, HierarchyLevel \par \b I/O\/ \: None -> DocumentContent \par \b Complexity\/ \: 3
get_encoding()
Optional[str] dedoc.utils.utils.get_encoding (str path, str default = None)
\par \b Purpose\/ \: To detect the character encoding of a file (including gzip-compressed), enabling correct text extraction from diverse document sources.
\par \b Uses\/ \: gzip, charset_normalizer \par \b I/O\/ \: (str, Optional[str]) -> Optional[str] \par \b Complexity\/ \: 6
get_extensions_by_mime()
List[str] dedoc.utils.utils.get_extensions_by_mime (str mime)
\par \b Purpose\/ \: To retrieve all known file extensions for a given MIME type.
\par \b Uses\/ \: mimetypes \par \b I/O\/ \: str -> List[str] \par \b Complexity\/ \: 2
Referenced by dedoc.utils.utils.get_extensions_by_mimes().
get_extensions_by_mimes()
List[str] dedoc.utils.utils.get_extensions_by_mimes (Set[str] mimes)
\par \b Purpose\/ \: To aggregate all file extensions for a set of MIME types, useful for filtering input by multiple accepted formats.
\par \b Uses\/ \: get_extensions_by_mime \par \b I/O\/ \: Set[str] -> List[str] \par \b Complexity\/ \: 3
References dedoc.utils.utils.get_extensions_by_mime().
get_file_mime_by_content()
str dedoc.utils.utils.get_file_mime_by_content (str path)
\par \b Purpose\/ \: To determine the MIME type by inspecting file content bytes (magic number detection), falling back to puremagic when libmagic returns octet-stream.
\par \b Uses\/ \: magic, puremagic \par \b I/O\/ \: str -> str \par \b Complexity\/ \: 6
get_file_mime_type()
str dedoc.utils.utils.get_file_mime_type (str path)
\par \b Purpose\/ \: To detect the MIME type of a file from its path/extension using the mimetypes standard library.
\par \b Uses\/ \: mimetypes \par \b I/O\/ \: str -> str \par \b Complexity\/ \: 3
Referenced by dedoc.utils.utils.get_mime_extension().
get_mime_extension()
Tuple[str, str] dedoc.utils.utils.get_mime_extension (Optional[str] file_path = None, Optional[str] mime = None, Optional[str] extension = None)
\par \b Purpose\/ \: To resolve the MIME type and file extension from a file path or explicit parameters, providing a single entry point for file type identification throughout the pipeline.
\par \b Uses\/ \: splitext_, get_file_mime_type \par \b I/O\/ \: (Optional[str], Optional[str], Optional[str]) -> Tuple[str, str] \par \b Complexity\/ \: 5
References dedoc.utils.utils.get_file_mime_type(), and dedoc.utils.utils.splitext_().
get_unique_name()
str dedoc.utils.utils.get_unique_name (str filename)
\par \b Purpose\/ \: To generate a collision-resistant unique filename using a timestamp and random suffix, ensuring safe concurrent file writes.
\par \b Uses\/ \: splitext_, time, random \par \b I/O\/ \: str -> str \par \b Complexity\/ \: 4
References dedoc.utils.utils.splitext_().
Referenced by dedoc.utils.utils.save_data_to_unique_file().
identity()
T dedoc.utils.utils.identity (T x)
\par \b Purpose\/ \: To return its input unchanged, serving as a no-op transform in functional pipelines.
\par \b I/O\/ \: T -> T \par \b Complexity\/ \: 1
list_get()
Optional[T] dedoc.utils.utils.list_get (List[T] ls, int index, Optional[T] default = None)
\par \b Purpose\/ \: To safely access list elements by index, returning a default value when the index is out of bounds.
\par \b Uses\/ \: typing \par \b I/O\/ \: (List[T], int, Optional[T]) -> Optional[T] \par \b Complexity\/ \: 2
save_data_to_unique_file()
str dedoc.utils.utils.save_data_to_unique_file (str directory, str filename, bytes binary_data)
\par \b Purpose\/ \: To write binary data to a uniquely-named file in a target directory, avoiding collisions from concurrent writes.
\par \b Uses\/ \: get_unique_name \par \b I/O\/ \: (str, str, bytes) -> str \par \b Complexity\/ \: 4
References dedoc.utils.utils.get_unique_name().
save_upload_file()
str dedoc.utils.utils.save_upload_file (UploadFile upload_file, str output_dir)
\par \b Purpose\/ \: To persist an uploaded file from a FastAPI endpoint to disk with filename length validation, ensuring safe storage before processing.
\par \b Uses\/ \: shutil, check_filename_length \par \b I/O\/ \: (UploadFile, str) -> str \par \b Complexity\/ \: 5
References dedoc.utils.utils.check_filename_length().
send_file()
Dict[str, Any] dedoc.utils.utils.send_file (str host, str file_name, str file_path, dict parameters)
\par \b Purpose\/ \: To send a file via HTTP POST multipart upload to a remote dedoc endpoint, enabling distributed document processing.
\par \b Uses\/ \: requests, json \par \b I/O\/ \: (str, str, str, dict) -> Dict[str, Any] \par \b Complexity\/ \: 5
similarity()
float dedoc.utils.utils.similarity (str s1, str s2)
\par \b Purpose\/ \: To compute a case-insensitive string similarity ratio using difflib.SequenceMatcher, enabling fuzzy text matching.
\par \b Uses\/ \: difflib \par \b I/O\/ \: (str, str) -> float \par \b Complexity\/ \: 4
similarity_levenshtein()
float dedoc.utils.utils.similarity_levenshtein (str str1, str str2)
\par \b Purpose\/ \: To compute a case-insensitive Levenshtein ratio for high-quality fuzzy string comparison.
\par \b Uses\/ \: Levenshtein \par \b I/O\/ \: (str, str) -> float \par \b Complexity\/ \: 4
special_match()
bool dedoc.utils.utils.special_match (str strg, str regular_pattern = r"[^.?!,:;'\"\n\r ]")
\par \b Purpose\/ \: To check if a string consists only of a specific character class (default: non-punctuation), used for content validation.
\par \b Uses\/ \: re \par \b I/O\/ \: (str, str) -> bool \par \b Complexity\/ \: 3
splitext_()
Tuple[str, str] dedoc.utils.utils.splitext_ (str path)
\par \b Purpose\/ \: To split a filename into (name, extension) correctly handling multi-dot extensions like .tar.gz that are common in compressed document formats.
\par \b Uses\/ \: os.path \par \b I/O\/ \: str -> Tuple[str, str] \par \b Complexity\/ \: 4
Referenced by dedoc.utils.utils.check_filename_length(), dedoc.utils.utils.get_mime_extension(), and dedoc.utils.utils.get_unique_name().
Variable Documentation
double_dot_extensions
tuple dedoc.utils.utils.double_dot_extensions = (".txt.gz", ".tar.gz", ".mht.gz", ".mhtml.gz", ".note.pickle")
logger
dedoc.utils.utils.logger = logging.getLogger(__name__)
T
dedoc.utils.utils.T = TypeVar("T")