Dedoc: dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells Namespace Reference
dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells Namespace Reference
Functions
List[List[Cell]] split_last_column (List[List[Cell]] matrix_table, str language, np.array image)
List[List[Cell]] _split_each_row (List[Cell] union_cells, List[List[Cell]] matrix_table, str language, np.array image)
List[Cell] _split_row (Cell cell_splitter, List[Cell] union_cell, str language, np.array image)
List[LineWithMeta] __get_ocr_lines (np.ndarray cell_image, str language, np.ndarray page_image, BBox cell_bbox, int padding_cell_value)
_module_contract ()
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
Variables
logger = logging.getLogger(__name__)
Function Documentation
__get_ocr_lines()
List[LineWithMeta] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells.__get_ocr_lines (np.ndarray cell_image, str language, np.ndarray page_image, BBox cell_bbox, int padding_cell_value) private
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells._split_row().
_module_contract()
dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells._module_contract () protected
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
\par \b Scope\/ \: Table recognition and extraction from document images. \par \b Input\/ \: [File path (str), parameters (Optional[dict]) — document on disk.] \par \b Output\/ \: [UnstructuredDocument with lines, tables, attachments, and warnings.] \par \b Links\/ \: [USES_API(9): dedoc.data_structures.*; USES_API(8): dedoc.readers.BaseReader] \par \b Invariants\/ \:
read() ALWAYS returns an UnstructuredDocument. \par \b Rationale\/ \:
Q: Why is this reader separated from others? A: Each reader handles one format family — isolation prevents format coupling and simplifies extension. \par \b Changes\/ \:
LAST_CHANGE: [v1.0.0 – Added SEMANTIC TEMPLATE markup and LDD logging.] \par \b Module Map\/ \:
FUNC [5][split_last_column utility/helper] => split_last_column FUNC [5][_split_each_row utility/helper] => _split_each_row FUNC [5][_split_row utility/helper] => _split_row FUNC [5][__get_ocr_lines utility/helper] => __get_ocr_lines \par \b Use Cases\/ \:
[read]: System (Pipeline) → ParseDocument(PDF) → UnstructuredDocument
_split_each_row()
List[List[Cell]] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells._split_each_row (List[Cell] union_cells, List[List[Cell]] matrix_table, str language, np.array image) protected
References dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells._split_row().
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells.split_last_column().
_split_row()
List[Cell] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells._split_row (Cell cell_splitter, List[Cell] union_cell, str language, np.array image) protected
References dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells.__get_ocr_lines().
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells._split_each_row().
split_last_column()
List[List[Cell]] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells.split_last_column (List[List[Cell]] matrix_table, str language, np.array image)
  A         B       C       D
| | Cell1 | word1 | ---------------— | |
| | Cell2 | word2 |
| | | | |
| | | | |
We need split last union column (C and D position) by y coordinates of column B. We don't want simple copy all text "word1\nword2". We want split with correct content. Result below:
A B C D
| | | word1 | word1 | ---------------— |-----— |----— |
| | | word2 | word1 |
| | | | |
| | | | |
References dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells._split_each_row().
Variable Documentation
logger
dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.split_last_hor_union_cells.logger = logging.getLogger(__name__)