var namespacededoc_1_1structure__extractors_1_1concrete__structure__extractors_1_1tz__structure__extractor =
[
    [ "TzStructureExtractor", "classdedoc_1_1structure__extractors_1_1concrete__structure__extractors_1_1tz__structure__extractor_1_1TzStructureExtractor.html", "classdedoc_1_1structure__extractors_1_1concrete__structure__extractors_1_1tz__structure__extractor_1_1TzStructureExtractor" ],
    [ "_module_contract", "namespacededoc_1_1structure__extractors_1_1concrete__structure__extractors_1_1tz__structure__extractor.html#aa4d6a5e67b3676ac3c1dc24b0d5a8adf", null ],
    [ "logger", "namespacededoc_1_1structure__extractors_1_1concrete__structure__extractors_1_1tz__structure__extractor.html#a5ddcc1ecbba2f2072bb21179b02e8d3b", null ]
];