var namespacededoc_1_1metadata__extractors_1_1concrete__metadata__extractors_1_1docx__metadata__extractor =
[
    [ "DocxMetadataExtractor", "classdedoc_1_1metadata__extractors_1_1concrete__metadata__extractors_1_1docx__metadata__extractor_1_1DocxMetadataExtractor.html", "classdedoc_1_1metadata__extractors_1_1concrete__metadata__extractors_1_1docx__metadata__extractor_1_1DocxMetadataExtractor" ],
    [ "_module_contract", "namespacededoc_1_1metadata__extractors_1_1concrete__metadata__extractors_1_1docx__metadata__extractor.html#a241a9ff2da388fbb2349bedb98d60c70", null ]
];