Dedoc: dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing Namespace Reference
dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing Namespace Reference
Functions
np.ndarray rotate_with_threshold (np.ndarray img, float angle, float threshold=None, *dict config)
rotates a table image and saving image.shape during rotation.
Tuple[np.ndarray, int] apply_houph_line (np.ndarray img, int threshold_gap=10, *dict config)
[Any, Any, np.ndarray, float] get_contours_cells (np.ndarray img, str table_type, *dict config)
function's steps: 1) detects Houph lines for detecting rotate angle.
[Any, Any] __get_contours_for_table_wo_external_bounds (np.ndarray img, np.ndarray img_with_contours, List contours, List hierarchy, dict config)
bool __filter_table (np.ndarray image, np.ndarray table_image)
[np.ndarray, np.ndarray] __get_table_contours (np.ndarray contours, List hierarchy)
[np.ndarray, float] __apply_houph_lines_and_detect_angle (np.ndarray image, dict config)
np.ndarray detect_horizontal_and_vertical_lines (np.ndarray img_bin, dict config, str task)
np.ndarray __paint_bounds (np.ndarray image)
[TableTree, List[np.ndarray], float] detect_tables_by_contours (np.ndarray img, str language="rus", str table_type="", *dict config)
detecting contours and TreeTable with help contour analysis.
_module_contract ()
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
Variables
logger = get_config().get("logger", logging.getLogger())
table_options = TableTypeAdditionalOptions()
float ROTATE_THRESHOLD = 0.3
Function Documentation
__apply_houph_lines_and_detect_angle()
[np.ndarray, float] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__apply_houph_lines_and_detect_angle (np.ndarray image, dict config) private
References dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.apply_houph_line().
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.get_contours_cells().
__filter_table()
bool dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__filter_table (np.ndarray image, np.ndarray table_image) private
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__get_contours_for_table_wo_external_bounds().
__get_contours_for_table_wo_external_bounds()
[Any, Any] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__get_contours_for_table_wo_external_bounds (np.ndarray img, np.ndarray img_with_contours, List contours, List hierarchy, dict config) private
References dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__filter_table(), and dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__get_table_contours().
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.get_contours_cells().
__get_table_contours()
[np.ndarray, np.ndarray] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__get_table_contours (np.ndarray contours, List hierarchy) private
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__get_contours_for_table_wo_external_bounds().
__paint_bounds()
np.ndarray dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__paint_bounds (np.ndarray image) private
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.get_contours_cells().
_module_contract()
dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing._module_contract () protected
\par \b Module Contract\/ \:\par \b Purpose\/ \: Read and parse PDF documents, extracting lines with metadata, tables, and attachments into UnstructuredDocument.
\par \b Scope\/ \: Table recognition and extraction from document images. \par \b Input\/ \: [File path (str), parameters (Optional[dict]) — document on disk.] \par \b Output\/ \: [UnstructuredDocument with lines, tables, attachments, and warnings.] \par \b Links\/ \: [USES_API(9): dedoc.data_structures.*; USES_API(8): dedoc.readers.BaseReader] \par \b Invariants\/ \:
read() ALWAYS returns an UnstructuredDocument. \par \b Rationale\/ \:
Q: Why is this reader separated from others? A: Each reader handles one format family — isolation prevents format coupling and simplifies extension. \par \b Changes\/ \:
LAST_CHANGE: [v1.0.0 – Added SEMANTIC TEMPLATE markup and LDD logging.] \par \b Module Map\/ \:
FUNC [5][rotate_with_threshold utility/helper] => rotate_with_threshold FUNC [5][apply_houph_line utility/helper] => apply_houph_line FUNC [5][get_contours_cells utility/helper] => get_contours_cells FUNC [5][__get_contours_for_table_wo_external_bounds utility/helper] => __get_contours_for_table_wo_external_bounds FUNC [5][__filter_table utility/helper] => __filter_table FUNC [5][__get_table_contours utility/helper] => __get_table_contours FUNC [5][__apply_houph_lines_and_detect_angle utility/helper] => __apply_houph_lines_and_detect_angle FUNC [5][detect_horizontal_and_vertical_lines utility/helper] => detect_horizontal_and_vertical_lines FUNC [5][__paint_bounds utility/helper] => __paint_bounds FUNC [5][detect_tables_by_contours utility/helper] => detect_tables_by_contours \par \b Use Cases\/ \:
[read]: System (Pipeline) → ParseDocument(PDF) → UnstructuredDocument
apply_houph_line()
Tuple[np.ndarray, int] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.apply_houph_line (np.ndarray img, int threshold_gap = 10, *dict config)
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__apply_houph_lines_and_detect_angle().
detect_horizontal_and_vertical_lines()
np.ndarray dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.detect_horizontal_and_vertical_lines (np.ndarray img_bin, dict config, str task)
detect_tables_by_contours()
[TableTree, List[np.ndarray], float] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.detect_tables_by_contours (np.ndarray img, str language = "rus", str table_type = "", *dict config)
detecting contours and TreeTable with help contour analysis.
TreeTable is :param img: input image :param language: parameter language for Tesseract :param config: dict from config.py :return: TreeTable, contour, rotate angle
References dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.get_contours_cells().
get_contours_cells()
[Any, Any, np.ndarray, float] dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.get_contours_cells (np.ndarray img, str table_type, *dict config)
function's steps: 1) detects Houph lines for detecting rotate angle.
Then input image has rotated on the rotate angle. 2) performs morphological operations under rotated images for detecting horizontal and vertical lines 3) on found lines detects tree contours with help cv2.findContours :param img: input image :param config: dict from config.py :return: contours, contours's hierarchy, rotated image, rotate angle
References dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__apply_houph_lines_and_detect_angle(), dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__get_contours_for_table_wo_external_bounds(), dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.__paint_bounds(), and dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.rotate_with_threshold().
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.detect_tables_by_contours().
rotate_with_threshold()
np.ndarray dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.rotate_with_threshold (np.ndarray img, float angle, float threshold = None, *dict config)
rotates a table image and saving image.shape during rotation.
It is important for word bounding box extraction
Referenced by dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.get_contours_cells().
Variable Documentation
logger
dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.logger = get_config().get("logger", logging.getLogger())
ROTATE_THRESHOLD
float dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.ROTATE_THRESHOLD = 0.3
table_options
dedoc.readers.pdf_reader.pdf_image_reader.table_recognizer.table_utils.img_processing.table_options = TableTypeAdditionalOptions()