var searchData=
[
  ['tabby_5fpdf_5ferror_2epy_0',['tabby_pdf_error.py',['../tabby__pdf__error_8py.html',1,'']]],
  ['tabbypdf_2epy_1',['tabbypdf.py',['../tabbypdf_8py.html',1,'']]],
  ['table_2epy_2',['table.py',['../data__structures_2table_8py.html',1,'(Global Namespace)'],['../readers_2docx__reader_2data__structures_2table_8py.html',1,'(Global Namespace)'],['../readers_2pptx__reader_2table_8py.html',1,'(Global Namespace)'],['../api_2schema_2table_8py.html',1,'(Global Namespace)']]],
  ['table_5fannotation_2epy_3',['table_annotation.py',['../table__annotation_8py.html',1,'']]],
  ['table_5fattribute_5fextractor_2epy_4',['table_attribute_extractor.py',['../table__attribute__extractor_8py.html',1,'']]],
  ['table_5fmetadata_2epy_5',['table_metadata.py',['../data__structures_2table__metadata_8py.html',1,'(Global Namespace)'],['../api_2schema_2table__metadata_8py.html',1,'(Global Namespace)']]],
  ['table_5frecognizer_2epy_6',['table_recognizer.py',['../table__recognizer_8py.html',1,'']]],
  ['table_5ftree_2epy_7',['table_tree.py',['../table__tree_8py.html',1,'']]],
  ['table_5ftype_2epy_8',['table_type.py',['../table__type_8py.html',1,'']]],
  ['tag_5fheader_5fpattern_2epy_9',['tag_header_pattern.py',['../tag__header__pattern_8py.html',1,'']]],
  ['tag_5flist_5fpattern_2epy_10',['tag_list_pattern.py',['../tag__list__pattern_8py.html',1,'']]],
  ['tag_5fpattern_2epy_11',['tag_pattern.py',['../tag__pattern_8py.html',1,'']]],
  ['tesseract_5fengine_2epy_12',['tesseract_engine.py',['../tesseract__engine_8py.html',1,'']]],
  ['text_5fwith_5fbbox_2epy_13',['text_with_bbox.py',['../text__with__bbox_8py.html',1,'']]],
  ['toc_5fbuilder_2epy_14',['toc_builder.py',['../toc__builder_8py.html',1,'']]],
  ['toc_5ffeature_5fextractor_2epy_15',['toc_feature_extractor.py',['../toc__feature__extractor_8py.html',1,'']]],
  ['train_5fdataset_5futils_2epy_16',['train_dataset_utils.py',['../train__dataset__utils_8py.html',1,'']]],
  ['transforms_2epy_17',['transforms.py',['../transforms_8py.html',1,'']]],
  ['tree_5fconstructor_2epy_18',['tree_constructor.py',['../tree__constructor_8py.html',1,'']]],
  ['tree_5fnode_2epy_19',['tree_node.py',['../data__structures_2tree__node_8py.html',1,'(Global Namespace)'],['../api_2schema_2tree__node_8py.html',1,'(Global Namespace)']]],
  ['txt_5fconverter_2epy_20',['txt_converter.py',['../txt__converter_8py.html',1,'']]],
  ['txtlayer_5fdetector_2epy_21',['txtlayer_detector.py',['../txtlayer__detector_8py.html',1,'']]],
  ['txtlayer_5ffeature_5fextractor_2epy_22',['txtlayer_feature_extractor.py',['../txtlayer__feature__extractor_8py.html',1,'']]],
  ['txtlayer_5fresult_2epy_23',['txtlayer_result.py',['../txtlayer__result_8py.html',1,'']]],
  ['tz_5fclassifier_2epy_24',['tz_classifier.py',['../tz__classifier_8py.html',1,'']]],
  ['tz_5ffeature_5fextractor_2epy_25',['tz_feature_extractor.py',['../tz__feature__extractor_8py.html',1,'']]],
  ['tz_5fstructure_5fextractor_2epy_26',['tz_structure_extractor.py',['../tz__structure__extractor_8py.html',1,'']]]
];
