var searchData=
[
  ['page_5fwith_5fbboxes_2epy_0',['page_with_bboxes.py',['../page__with__bboxes_8py.html',1,'']]],
  ['paired_5ffeature_5fextractor_2epy_1',['paired_feature_extractor.py',['../paired__feature__extractor_8py.html',1,'']]],
  ['paragraph_2epy_2',['paragraph.py',['../docx__reader_2data__structures_2paragraph_8py.html',1,'(Global Namespace)'],['../pptx__reader_2paragraph_8py.html',1,'(Global Namespace)']]],
  ['paragraph_5ffeature_5fextractor_2epy_3',['paragraph_feature_extractor.py',['../paragraph__feature__extractor_8py.html',1,'']]],
  ['parameter_5futils_2epy_4',['parameter_utils.py',['../parameter__utils_8py.html',1,'']]],
  ['parsed_5fdocument_2epy_5',['parsed_document.py',['../api_2schema_2parsed__document_8py.html',1,'(Global Namespace)'],['../data__structures_2parsed__document_8py.html',1,'(Global Namespace)']]],
  ['pattern_5fcomposition_2epy_6',['pattern_composition.py',['../pattern__composition_8py.html',1,'']]],
  ['pdf_5fattachments_5fextractor_2epy_7',['pdf_attachments_extractor.py',['../pdf__attachments__extractor_8py.html',1,'']]],
  ['pdf_5fauto_5freader_2epy_8',['pdf_auto_reader.py',['../pdf__auto__reader_8py.html',1,'']]],
  ['pdf_5fbase_5freader_2epy_9',['pdf_base_reader.py',['../pdf__base__reader_8py.html',1,'']]],
  ['pdf_5fbroken_5fencoding_5freader_2epy_10',['pdf_broken_encoding_reader.py',['../pdf__broken__encoding__reader_8py.html',1,'']]],
  ['pdf_5fconverter_2epy_11',['pdf_converter.py',['../pdf__converter_8py.html',1,'']]],
  ['pdf_5fimage_5fattachment_2epy_12',['pdf_image_attachment.py',['../pdf__image__attachment_8py.html',1,'']]],
  ['pdf_5fimage_5freader_2epy_13',['pdf_image_reader.py',['../pdf__image__reader_8py.html',1,'']]],
  ['pdf_5flayout_5fcorrector_2epy_14',['pdf_layout_corrector.py',['../pdf__layout__corrector_8py.html',1,'']]],
  ['pdf_5fmetadata_5fextractor_2epy_15',['pdf_metadata_extractor.py',['../pdf__metadata__extractor_8py.html',1,'']]],
  ['pdf_5ftabby_5freader_2epy_16',['pdf_tabby_reader.py',['../pdf__tabby__reader_8py.html',1,'']]],
  ['pdf_5ftxtlayer_5freader_2epy_17',['pdf_txtlayer_reader.py',['../pdf__txtlayer__reader_8py.html',1,'']]],
  ['pdf_5futils_2epy_18',['pdf_utils.py',['../pdf__utils_8py.html',1,'']]],
  ['pdfminer_5fextractor_2epy_19',['pdfminer_extractor.py',['../pdfminer__extractor_8py.html',1,'']]],
  ['pdfminer_5futils_2epy_20',['pdfminer_utils.py',['../pdfminer__utils_8py.html',1,'']]],
  ['png_5fconverter_2epy_21',['png_converter.py',['../png__converter_8py.html',1,'']]],
  ['pptx_5fattachments_5fextractor_2epy_22',['pptx_attachments_extractor.py',['../pptx__attachments__extractor_8py.html',1,'']]],
  ['pptx_5fconverter_2epy_23',['pptx_converter.py',['../pptx__converter_8py.html',1,'']]],
  ['pptx_5freader_2epy_24',['pptx_reader.py',['../pptx__reader_8py.html',1,'']]],
  ['prefix_2epy_25',['prefix.py',['../prefix_8py.html',1,'']]],
  ['process_5fhandler_2epy_26',['process_handler.py',['../process__handler_8py.html',1,'']]],
  ['properties_5fextractor_2epy_27',['properties_extractor.py',['../pptx__reader_2properties__extractor_8py.html',1,'(Global Namespace)'],['../docx__reader_2properties__extractor_8py.html',1,'(Global Namespace)']]]
];
